package item

type ItemInfo struct {
	ID   int
	Data int
}

var ItemNames = map[string]ItemInfo{
	"air":           {ID: 0, Data: 0},
	"stone":         {ID: 1, Data: 0},
	"grass":         {ID: 2, Data: 0},
	"dirt":          {ID: 3, Data: 0},
	"dirt:1":        {ID: 3, Data: 1},
	"dirt:2":        {ID: 3, Data: 2},
	"cobblestone":   {ID: 4, Data: 0},
	"planks":        {ID: 5, Data: 0},
	"planks:1":      {ID: 5, Data: 1},
	"planks:2":      {ID: 5, Data: 2},
	"planks:3":      {ID: 5, Data: 3},
	"planks:4":      {ID: 5, Data: 4},
	"planks:5":      {ID: 5, Data: 5},
	"sapling":       {ID: 6, Data: 0},
	"bedrock":       {ID: 7, Data: 0},
	"flowing_water": {ID: 8, Data: 0},
	"water":         {ID: 9, Data: 0},
	"flowing_lava":  {ID: 10, Data: 0},
	"lava":          {ID: 11, Data: 0},
	"sand":          {ID: 12, Data: 0},
	"sand:1":        {ID: 12, Data: 1},
	"gravel":        {ID: 13, Data: 0},
	"gold_ore":      {ID: 14, Data: 0},
	"iron_ore":      {ID: 15, Data: 0},
	"coal_ore":      {ID: 16, Data: 0},
	"log":           {ID: 17, Data: 0},
	"log:1":         {ID: 17, Data: 1},
	"log:2":         {ID: 17, Data: 2},
	"log:3":         {ID: 17, Data: 3},
	"log:4":         {ID: 17, Data: 4},
	"log:5":         {ID: 17, Data: 5},
	"log:6":         {ID: 17, Data: 6},
	"log:7":         {ID: 17, Data: 7},
	"log:8":         {ID: 17, Data: 8},
	"log:9":         {ID: 17, Data: 9},
	"log:10":        {ID: 17, Data: 10},
	"log:11":        {ID: 17, Data: 11},
	"leaves":        {ID: 18, Data: 0},
	"leaves:1":      {ID: 18, Data: 1},
	"leaves:2":      {ID: 18, Data: 2},
	"leaves:3":      {ID: 18, Data: 3},
	"leaves:4":      {ID: 18, Data: 4},
	"leaves:5":      {ID: 18, Data: 5},
	"leaves:6":      {ID: 18, Data: 6},
	"leaves:7":      {ID: 18, Data: 7},
	"leaves:8":      {ID: 18, Data: 8},
	"leaves:9":      {ID: 18, Data: 9},
	"leaves:10":     {ID: 18, Data: 10},
	"leaves:11":     {ID: 18, Data: 11},
	"leaves:12":     {ID: 18, Data: 12},
	"leaves:13":     {ID: 18, Data: 13},
	"leaves:14":     {ID: 18, Data: 14},
	"leaves:15":     {ID: 18, Data: 15},
	"sponge":        {ID: 19, Data: 0},
	"sponge:1":      {ID: 19, Data: 1},
	"glass":         {ID: 20, Data: 0},
	"lapis_ore":     {ID: 21, Data: 0},
	"lapis_block":   {ID: 22, Data: 0},
	"dispenser":     {ID: 23, Data: 0},
	"sandstone":     {ID: 24, Data: 0},
	"sandstone:1":   {ID: 24, Data: 1},
	"sandstone:2":   {ID: 24, Data: 2},
	"noteblock":     {ID: 25, Data: 0},
	//"bed":                  {ID: 26, Data: 0},
	"bed:1":                {ID: 26, Data: 1},
	"bed:2":                {ID: 26, Data: 2},
	"bed:3":                {ID: 26, Data: 3},
	"bed:8":                {ID: 26, Data: 8},
	"bed:9":                {ID: 26, Data: 9},
	"bed:10":               {ID: 26, Data: 10},
	"bed:11":               {ID: 26, Data: 11},
	"golden_rail":          {ID: 27, Data: 0},
	"golden_rail:1":        {ID: 27, Data: 1},
	"golden_rail:2":        {ID: 27, Data: 2},
	"golden_rail:3":        {ID: 27, Data: 3},
	"golden_rail:4":        {ID: 27, Data: 4},
	"golden_rail:5":        {ID: 27, Data: 5},
	"golden_rail:8":        {ID: 27, Data: 8},
	"golden_rail:9":        {ID: 27, Data: 9},
	"golden_rail:10":       {ID: 27, Data: 10},
	"golden_rail:11":       {ID: 27, Data: 11},
	"golden_rail:12":       {ID: 27, Data: 12},
	"golden_rail:13":       {ID: 27, Data: 13},
	"detector_rail":        {ID: 28, Data: 0},
	"detector_rail:1":      {ID: 28, Data: 1},
	"detector_rail:2":      {ID: 28, Data: 2},
	"detector_rail:3":      {ID: 28, Data: 3},
	"detector_rail:4":      {ID: 28, Data: 4},
	"detector_rail:5":      {ID: 28, Data: 5},
	"detector_rail:8":      {ID: 28, Data: 8},
	"detector_rail:9":      {ID: 28, Data: 9},
	"detector_rail:10":     {ID: 28, Data: 10},
	"detector_rail:11":     {ID: 28, Data: 11},
	"detector_rail:12":     {ID: 28, Data: 12},
	"detector_rail:13":     {ID: 28, Data: 13},
	"sticky_piston":        {ID: 29, Data: 0},
	"sticky_piston:1":      {ID: 29, Data: 1},
	"sticky_piston:2":      {ID: 29, Data: 2},
	"sticky_piston:3":      {ID: 29, Data: 3},
	"sticky_piston:4":      {ID: 29, Data: 4},
	"sticky_piston:5":      {ID: 29, Data: 5},
	"sticky_piston:8":      {ID: 29, Data: 8},
	"sticky_piston:9":      {ID: 29, Data: 9},
	"sticky_piston:10":     {ID: 29, Data: 10},
	"sticky_piston:11":     {ID: 29, Data: 11},
	"sticky_piston:12":     {ID: 29, Data: 12},
	"sticky_piston:13":     {ID: 29, Data: 13},
	"web":                  {ID: 30, Data: 0},
	"tallgrass":            {ID: 31, Data: 0},
	"tallgrass:1":          {ID: 31, Data: 1},
	"tallgrass:2":          {ID: 31, Data: 2},
	"deadbush":             {ID: 32, Data: 0},
	"piston":               {ID: 33, Data: 0},
	"piston:1":             {ID: 33, Data: 1},
	"piston:2":             {ID: 33, Data: 2},
	"piston:3":             {ID: 33, Data: 3},
	"piston:4":             {ID: 33, Data: 4},
	"piston:5":             {ID: 33, Data: 5},
	"piston:8":             {ID: 33, Data: 8},
	"piston:9":             {ID: 33, Data: 9},
	"piston:10":            {ID: 33, Data: 10},
	"piston:11":            {ID: 33, Data: 11},
	"piston:12":            {ID: 33, Data: 12},
	"piston:13":            {ID: 33, Data: 13},
	"piston_head":          {ID: 34, Data: 0},
	"piston_head:1":        {ID: 34, Data: 1},
	"piston_head:2":        {ID: 34, Data: 2},
	"piston_head:3":        {ID: 34, Data: 3},
	"piston_head:4":        {ID: 34, Data: 4},
	"piston_head:5":        {ID: 34, Data: 5},
	"piston_head:8":        {ID: 34, Data: 8},
	"piston_head:9":        {ID: 34, Data: 9},
	"piston_head:10":       {ID: 34, Data: 10},
	"piston_head:11":       {ID: 34, Data: 11},
	"piston_head:12":       {ID: 34, Data: 12},
	"piston_head:13":       {ID: 34, Data: 13},
	"wool":                 {ID: 35, Data: 0},
	"wool:1":               {ID: 35, Data: 1},
	"wool:2":               {ID: 35, Data: 2},
	"wool:3":               {ID: 35, Data: 3},
	"wool:4":               {ID: 35, Data: 4},
	"wool:5":               {ID: 35, Data: 5},
	"wool:6":               {ID: 35, Data: 6},
	"wool:7":               {ID: 35, Data: 7},
	"wool:8":               {ID: 35, Data: 8},
	"wool:9":               {ID: 35, Data: 9},
	"wool:10":              {ID: 35, Data: 10},
	"wool:11":              {ID: 35, Data: 11},
	"wool:12":              {ID: 35, Data: 12},
	"wool:13":              {ID: 35, Data: 13},
	"wool:14":              {ID: 35, Data: 14},
	"wool:15":              {ID: 35, Data: 15},
	"piston_extension":     {ID: 36, Data: 0},
	"yellow_flower":        {ID: 37, Data: 0},
	"red_flower":           {ID: 38, Data: 0},
	"red_flower:1":         {ID: 38, Data: 1},
	"red_flower:2":         {ID: 38, Data: 2},
	"red_flower:3":         {ID: 38, Data: 3},
	"red_flower:4":         {ID: 38, Data: 4},
	"red_flower:5":         {ID: 38, Data: 5},
	"red_flower:6":         {ID: 38, Data: 6},
	"red_flower:7":         {ID: 38, Data: 7},
	"red_flower:8":         {ID: 38, Data: 8},
	"brown_mushroom":       {ID: 39, Data: 0},
	"red_mushroom":         {ID: 40, Data: 0},
	"gold_block":           {ID: 41, Data: 0},
	"iron_block":           {ID: 42, Data: 0},
	"double_stone_slab":    {ID: 43, Data: 0},
	"double_stone_slab:1":  {ID: 43, Data: 1},
	"double_stone_slab:2":  {ID: 43, Data: 2},
	"double_stone_slab:3":  {ID: 43, Data: 3},
	"double_stone_slab:4":  {ID: 43, Data: 4},
	"double_stone_slab:5":  {ID: 43, Data: 5},
	"double_stone_slab:6":  {ID: 43, Data: 6},
	"double_stone_slab:7":  {ID: 43, Data: 7},
	"double_stone_slab:8":  {ID: 43, Data: 8},
	"double_stone_slab:9":  {ID: 43, Data: 9},
	"double_stone_slab:15": {ID: 43, Data: 15},
	"stone_slab":           {ID: 44, Data: 0},
	"stone_slab:1":         {ID: 44, Data: 1},
	"stone_slab:2":         {ID: 44, Data: 2},
	"stone_slab:3":         {ID: 44, Data: 3},
	"stone_slab:4":         {ID: 44, Data: 4},
	"stone_slab:5":         {ID: 44, Data: 5},
	"stone_slab:6":         {ID: 44, Data: 6},
	"stone_slab:7":         {ID: 44, Data: 7},
	"stone_slab:8":         {ID: 44, Data: 8},
	"stone_slab:9":         {ID: 44, Data: 9},
	"stone_slab:10":        {ID: 44, Data: 10},
	"stone_slab:11":        {ID: 44, Data: 11},
	"stone_slab:12":        {ID: 44, Data: 12},
	"stone_slab:13":        {ID: 44, Data: 13},
	"stone_slab:14":        {ID: 44, Data: 14},
	"stone_slab:15":        {ID: 44, Data: 15},
	"brick_block":          {ID: 45, Data: 0},
	"tnt":                  {ID: 46, Data: 0},
	"tnt:1":                {ID: 46, Data: 1},
	"bookshelf":            {ID: 47, Data: 0},
	"mossy_cobblestone":    {ID: 48, Data: 0},
	"obsidian":             {ID: 49, Data: 0},
	"torch":                {ID: 50, Data: 0},
	"torch:1":              {ID: 50, Data: 1},
	"torch:2":              {ID: 50, Data: 2},
	"torch:3":              {ID: 50, Data: 3},
	"torch:4":              {ID: 50, Data: 4},
	"fire":                 {ID: 51, Data: 0},
	"mob_spawner":          {ID: 52, Data: 0},
	"oak_stairs":           {ID: 53, Data: 0},
	"oak_stairs:1":         {ID: 53, Data: 1},
	"oak_stairs:2":         {ID: 53, Data: 2},
	"oak_stairs:3":         {ID: 53, Data: 3},
	"oak_stairs:4":         {ID: 53, Data: 4},
	"oak_stairs:5":         {ID: 53, Data: 5},
	"oak_stairs:6":         {ID: 53, Data: 6},
	"oak_stairs:7":         {ID: 53, Data: 7},
	"chest":                {ID: 54, Data: 0},
	"chest:2":              {ID: 54, Data: 2},
	"chest:3":              {ID: 54, Data: 3},
	"chest:4":              {ID: 54, Data: 4},
	"chest:5":              {ID: 54, Data: 5},
	"redstone_wire":        {ID: 55, Data: 0},
	"redstone_wire:1":      {ID: 55, Data: 1},
	"redstone_wire:2":      {ID: 55, Data: 2},
	"redstone_wire:3":      {ID: 55, Data: 3},
	"redstone_wire:4":      {ID: 55, Data: 4},
	"redstone_wire:5":      {ID: 55, Data: 5},
	"redstone_wire:6":      {ID: 55, Data: 6},
	"redstone_wire:7":      {ID: 55, Data: 7},
	"redstone_wire:8":      {ID: 55, Data: 8},
	"redstone_wire:9":      {ID: 55, Data: 9},
	"redstone_wire:10":     {ID: 55, Data: 10},
	"redstone_wire:11":     {ID: 55, Data: 11},
	"redstone_wire:12":     {ID: 55, Data: 12},
	"redstone_wire:13":     {ID: 55, Data: 13},
	"redstone_wire:14":     {ID: 55, Data: 14},
	"redstone_wire:15":     {ID: 55, Data: 15},
	"diamond_ore":          {ID: 56, Data: 0},
	"diamond_block":        {ID: 57, Data: 0},
	"crafting_table":       {ID: 58, Data: 0},
	//"wheat": {ID: 59, Data: 0},
	"wheat:1":          {ID: 59, Data: 1},
	"wheat:2":          {ID: 59, Data: 2},
	"wheat:3":          {ID: 59, Data: 3},
	"wheat:4":          {ID: 59, Data: 4},
	"wheat:5":          {ID: 59, Data: 5},
	"wheat:6":          {ID: 59, Data: 6},
	"wheat:7":          {ID: 59, Data: 7},
	"farmland":         {ID: 60, Data: 0},
	"farmland:1":       {ID: 60, Data: 1},
	"farmland:2":       {ID: 60, Data: 2},
	"farmland:3":       {ID: 60, Data: 3},
	"farmland:4":       {ID: 60, Data: 4},
	"farmland:5":       {ID: 60, Data: 5},
	"farmland:6":       {ID: 60, Data: 6},
	"farmland:7":       {ID: 60, Data: 7},
	"furnace":          {ID: 61, Data: 0},
	"furnace:2":        {ID: 61, Data: 2},
	"furnace:3":        {ID: 61, Data: 3},
	"furnace:4":        {ID: 61, Data: 4},
	"furnace:5":        {ID: 61, Data: 5},
	"lit_furnace:2":    {ID: 62, Data: 2},
	"lit_furnace:3":    {ID: 62, Data: 3},
	"lit_furnace:4":    {ID: 62, Data: 4},
	"lit_furnace:5":    {ID: 62, Data: 5},
	"standing_sign":    {ID: 63, Data: 0},
	"standing_sign:1":  {ID: 63, Data: 1},
	"standing_sign:2":  {ID: 63, Data: 2},
	"standing_sign:3":  {ID: 63, Data: 3},
	"standing_sign:4":  {ID: 63, Data: 4},
	"standing_sign:5":  {ID: 63, Data: 5},
	"standing_sign:6":  {ID: 63, Data: 6},
	"standing_sign:7":  {ID: 63, Data: 7},
	"standing_sign:8":  {ID: 63, Data: 8},
	"standing_sign:9":  {ID: 63, Data: 9},
	"standing_sign:10": {ID: 63, Data: 10},
	"standing_sign:11": {ID: 63, Data: 11},
	"standing_sign:12": {ID: 63, Data: 12},
	"standing_sign:13": {ID: 63, Data: 13},
	"standing_sign:14": {ID: 63, Data: 14},
	"standing_sign:15": {ID: 63, Data: 15},
	//"wooden_door": {ID: 64, Data: 0},
	"wooden_door:1":          {ID: 64, Data: 1},
	"wooden_door:2":          {ID: 64, Data: 2},
	"wooden_door:3":          {ID: 64, Data: 3},
	"wooden_door:4":          {ID: 64, Data: 4},
	"wooden_door:5":          {ID: 64, Data: 5},
	"wooden_door:6":          {ID: 64, Data: 6},
	"wooden_door:7":          {ID: 64, Data: 7},
	"wooden_door:8":          {ID: 64, Data: 8},
	"wooden_door:9":          {ID: 64, Data: 9},
	"ladder":                 {ID: 65, Data: 0},
	"ladder:2":               {ID: 65, Data: 2},
	"ladder:3":               {ID: 65, Data: 3},
	"ladder:4":               {ID: 65, Data: 4},
	"ladder:5":               {ID: 65, Data: 5},
	"rail":                   {ID: 66, Data: 0},
	"rail:1":                 {ID: 66, Data: 1},
	"rail:2":                 {ID: 66, Data: 2},
	"rail:3":                 {ID: 66, Data: 3},
	"rail:4":                 {ID: 66, Data: 4},
	"rail:5":                 {ID: 66, Data: 5},
	"rail:6":                 {ID: 66, Data: 6},
	"rail:7":                 {ID: 66, Data: 7},
	"rail:8":                 {ID: 66, Data: 8},
	"rail:9":                 {ID: 66, Data: 9},
	"stone_stairs":           {ID: 67, Data: 0},
	"stone_stairs:1":         {ID: 67, Data: 1},
	"stone_stairs:2":         {ID: 67, Data: 2},
	"stone_stairs:3":         {ID: 67, Data: 3},
	"stone_stairs:4":         {ID: 67, Data: 4},
	"stone_stairs:5":         {ID: 67, Data: 5},
	"stone_stairs:6":         {ID: 67, Data: 6},
	"stone_stairs:7":         {ID: 67, Data: 7},
	"wall_sign:2":            {ID: 68, Data: 2},
	"wall_sign:3":            {ID: 68, Data: 3},
	"wall_sign:4":            {ID: 68, Data: 4},
	"wall_sign:5":            {ID: 68, Data: 5},
	"lever":                  {ID: 69, Data: 0},
	"lever:1":                {ID: 69, Data: 1},
	"lever:2":                {ID: 69, Data: 2},
	"lever:3":                {ID: 69, Data: 3},
	"lever:4":                {ID: 69, Data: 4},
	"lever:5":                {ID: 69, Data: 5},
	"lever:6":                {ID: 69, Data: 6},
	"lever:7":                {ID: 69, Data: 7},
	"lever:8":                {ID: 69, Data: 8},
	"lever:9":                {ID: 69, Data: 9},
	"lever:10":               {ID: 69, Data: 10},
	"lever:11":               {ID: 69, Data: 11},
	"lever:12":               {ID: 69, Data: 12},
	"lever:13":               {ID: 69, Data: 13},
	"lever:14":               {ID: 69, Data: 14},
	"lever:15":               {ID: 69, Data: 15},
	"stone_pressure_plate":   {ID: 70, Data: 0},
	"stone_pressure_plate:1": {ID: 70, Data: 1},
	//"iron_door": {ID: 71, Data: 0},
	"iron_door:1":             {ID: 71, Data: 1},
	"iron_door:2":             {ID: 71, Data: 2},
	"iron_door:3":             {ID: 71, Data: 3},
	"iron_door:4":             {ID: 71, Data: 4},
	"iron_door:5":             {ID: 71, Data: 5},
	"iron_door:6":             {ID: 71, Data: 6},
	"iron_door:7":             {ID: 71, Data: 7},
	"iron_door:8":             {ID: 71, Data: 8},
	"iron_door:9":             {ID: 71, Data: 9},
	"wooden_pressure_plate":   {ID: 72, Data: 0},
	"wooden_pressure_plate:1": {ID: 72, Data: 1},
	"redstone_ore":            {ID: 73, Data: 0},
	"lit_redstone_ore":        {ID: 74, Data: 0},
	"unlit_redstone_torch":    {ID: 75, Data: 0},
	"unlit_redstone_torch:1":  {ID: 75, Data: 1},
	"unlit_redstone_torch:2":  {ID: 75, Data: 2},
	"unlit_redstone_torch:3":  {ID: 75, Data: 3},
	"unlit_redstone_torch:4":  {ID: 75, Data: 4},
	"redstone_torch":          {ID: 76, Data: 0},
	"redstone_torch:1":        {ID: 76, Data: 1},
	"redstone_torch:2":        {ID: 76, Data: 2},
	"redstone_torch:3":        {ID: 76, Data: 3},
	"redstone_torch:4":        {ID: 76, Data: 4},
	"stone_button":            {ID: 77, Data: 0},
	"snow_layer":              {ID: 78, Data: 0},
	"snow_layer:1":            {ID: 78, Data: 1},
	"snow_layer:2":            {ID: 78, Data: 2},
	"snow_layer:3":            {ID: 78, Data: 3},
	"snow_layer:4":            {ID: 78, Data: 4},
	"snow_layer:5":            {ID: 78, Data: 5},
	"snow_layer:6":            {ID: 78, Data: 6},
	"snow_layer:7":            {ID: 78, Data: 7},
	"ice":                     {ID: 79, Data: 0},
	"snow":                    {ID: 80, Data: 0},
	"cactus":                  {ID: 81, Data: 0},
	"clay":                    {ID: 82, Data: 0},
	//"reeds": {ID: 83, Data: 0},
	"jukebox":       {ID: 84, Data: 0},
	"jukebox:1":     {ID: 84, Data: 1},
	"fence":         {ID: 85, Data: 0},
	"pumpkin":       {ID: 86, Data: 0},
	"pumpkin:1":     {ID: 86, Data: 1},
	"pumpkin:2":     {ID: 86, Data: 2},
	"pumpkin:3":     {ID: 86, Data: 3},
	"netherrack":    {ID: 87, Data: 0},
	"soul_sand":     {ID: 88, Data: 0},
	"glowstone":     {ID: 89, Data: 0},
	"portal":        {ID: 90, Data: 0},
	"lit_pumpkin":   {ID: 91, Data: 0},
	"lit_pumpkin:1": {ID: 91, Data: 1},
	"lit_pumpkin:2": {ID: 91, Data: 2},
	"lit_pumpkin:3": {ID: 91, Data: 3},
	//"cake": {ID: 92, Data: 0},
	"cake:1":                  {ID: 92, Data: 1},
	"cake:2":                  {ID: 92, Data: 2},
	"cake:3":                  {ID: 92, Data: 3},
	"cake:4":                  {ID: 92, Data: 4},
	"cake:5":                  {ID: 92, Data: 5},
	"cake:6":                  {ID: 92, Data: 6},
	"unpowered_repeater":      {ID: 93, Data: 0},
	"unpowered_repeater:1":    {ID: 93, Data: 1},
	"unpowered_repeater:2":    {ID: 93, Data: 2},
	"unpowered_repeater:3":    {ID: 93, Data: 3},
	"unpowered_repeater:4":    {ID: 93, Data: 4},
	"unpowered_repeater:5":    {ID: 93, Data: 5},
	"unpowered_repeater:6":    {ID: 93, Data: 6},
	"unpowered_repeater:7":    {ID: 93, Data: 7},
	"unpowered_repeater:8":    {ID: 93, Data: 8},
	"unpowered_repeater:9":    {ID: 93, Data: 9},
	"unpowered_repeater:10":   {ID: 93, Data: 10},
	"unpowered_repeater:11":   {ID: 93, Data: 11},
	"unpowered_repeater:12":   {ID: 93, Data: 12},
	"unpowered_repeater:13":   {ID: 93, Data: 13},
	"unpowered_repeater:14":   {ID: 93, Data: 14},
	"unpowered_repeater:15":   {ID: 93, Data: 15},
	"powered_repeater":        {ID: 94, Data: 0},
	"powered_repeater:1":      {ID: 94, Data: 1},
	"powered_repeater:2":      {ID: 94, Data: 2},
	"powered_repeater:3":      {ID: 94, Data: 3},
	"powered_repeater:4":      {ID: 94, Data: 4},
	"powered_repeater:5":      {ID: 94, Data: 5},
	"powered_repeater:6":      {ID: 94, Data: 6},
	"powered_repeater:7":      {ID: 94, Data: 7},
	"powered_repeater:8":      {ID: 94, Data: 8},
	"powered_repeater:9":      {ID: 94, Data: 9},
	"powered_repeater:10":     {ID: 94, Data: 10},
	"powered_repeater:11":     {ID: 94, Data: 11},
	"powered_repeater:12":     {ID: 94, Data: 12},
	"powered_repeater:13":     {ID: 94, Data: 13},
	"powered_repeater:14":     {ID: 94, Data: 14},
	"powered_repeater:15":     {ID: 94, Data: 15},
	"stained_glass":           {ID: 95, Data: 0},
	"stained_glass:1":         {ID: 95, Data: 1},
	"stained_glass:2":         {ID: 95, Data: 2},
	"stained_glass:3":         {ID: 95, Data: 3},
	"stained_glass:4":         {ID: 95, Data: 4},
	"stained_glass:5":         {ID: 95, Data: 5},
	"stained_glass:6":         {ID: 95, Data: 6},
	"stained_glass:7":         {ID: 95, Data: 7},
	"stained_glass:8":         {ID: 95, Data: 8},
	"stained_glass:9":         {ID: 95, Data: 9},
	"stained_glass:10":        {ID: 95, Data: 10},
	"stained_glass:11":        {ID: 95, Data: 11},
	"stained_glass:12":        {ID: 95, Data: 12},
	"stained_glass:13":        {ID: 95, Data: 13},
	"stained_glass:14":        {ID: 95, Data: 14},
	"stained_glass:15":        {ID: 95, Data: 15},
	"trapdoor":                {ID: 96, Data: 0},
	"trapdoor:1":              {ID: 96, Data: 1},
	"trapdoor:2":              {ID: 96, Data: 2},
	"trapdoor:3":              {ID: 96, Data: 3},
	"trapdoor:4":              {ID: 96, Data: 4},
	"trapdoor:5":              {ID: 96, Data: 5},
	"trapdoor:6":              {ID: 96, Data: 6},
	"trapdoor:7":              {ID: 96, Data: 7},
	"trapdoor:8":              {ID: 96, Data: 8},
	"trapdoor:9":              {ID: 96, Data: 9},
	"trapdoor:10":             {ID: 96, Data: 10},
	"trapdoor:11":             {ID: 96, Data: 11},
	"trapdoor:12":             {ID: 96, Data: 12},
	"trapdoor:13":             {ID: 96, Data: 13},
	"trapdoor:14":             {ID: 96, Data: 14},
	"trapdoor:15":             {ID: 96, Data: 15},
	"monster_egg":             {ID: 97, Data: 0},
	"monster_egg:1":           {ID: 97, Data: 1},
	"monster_egg:2":           {ID: 97, Data: 2},
	"monster_egg:3":           {ID: 97, Data: 3},
	"monster_egg:4":           {ID: 97, Data: 4},
	"monster_egg:5":           {ID: 97, Data: 5},
	"stonebrick":              {ID: 98, Data: 0},
	"stonebrick:1":            {ID: 98, Data: 1},
	"stonebrick:2":            {ID: 98, Data: 2},
	"stonebrick:3":            {ID: 98, Data: 3},
	"brown_mushroom_block":    {ID: 99, Data: 0},
	"brown_mushroom_block:1":  {ID: 99, Data: 1},
	"brown_mushroom_block:2":  {ID: 99, Data: 2},
	"brown_mushroom_block:3":  {ID: 99, Data: 3},
	"brown_mushroom_block:4":  {ID: 99, Data: 4},
	"brown_mushroom_block:5":  {ID: 99, Data: 5},
	"brown_mushroom_block:6":  {ID: 99, Data: 6},
	"brown_mushroom_block:7":  {ID: 99, Data: 7},
	"brown_mushroom_block:8":  {ID: 99, Data: 8},
	"brown_mushroom_block:9":  {ID: 99, Data: 9},
	"brown_mushroom_block:10": {ID: 99, Data: 10},
	"brown_mushroom_block:14": {ID: 99, Data: 14},
	"brown_mushroom_block:15": {ID: 99, Data: 15},
	"red_mushroom_block":      {ID: 100, Data: 0},
	"red_mushroom_block:1":    {ID: 100, Data: 1},
	"red_mushroom_block:2":    {ID: 100, Data: 2},
	"red_mushroom_block:3":    {ID: 100, Data: 3},
	"red_mushroom_block:4":    {ID: 100, Data: 4},
	"red_mushroom_block:5":    {ID: 100, Data: 5},
	"red_mushroom_block:6":    {ID: 100, Data: 6},
	"red_mushroom_block:7":    {ID: 100, Data: 7},
	"red_mushroom_block:8":    {ID: 100, Data: 8},
	"red_mushroom_block:9":    {ID: 100, Data: 9},
	"red_mushroom_block:10":   {ID: 100, Data: 10},
	"red_mushroom_block:14":   {ID: 100, Data: 14},
	"red_mushroom_block:15":   {ID: 100, Data: 15},
	"iron_bars":               {ID: 101, Data: 0},
	"glass_pane":              {ID: 102, Data: 0},
	"melon_block":             {ID: 103, Data: 0},
	"pumpkin_stem":            {ID: 104, Data: 0},
	"pumpkin_stem:1":          {ID: 104, Data: 1},
	"pumpkin_stem:2":          {ID: 104, Data: 2},
	"pumpkin_stem:3":          {ID: 104, Data: 3},
	"pumpkin_stem:4":          {ID: 104, Data: 4},
	"pumpkin_stem:5":          {ID: 104, Data: 5},
	"pumpkin_stem:6":          {ID: 104, Data: 6},
	"pumpkin_stem:7":          {ID: 104, Data: 7},
	"melon_stem":              {ID: 105, Data: 0},
	"melon_stem:1":            {ID: 105, Data: 1},
	"melon_stem:2":            {ID: 105, Data: 2},
	"melon_stem:3":            {ID: 105, Data: 3},
	"melon_stem:4":            {ID: 105, Data: 4},
	"melon_stem:5":            {ID: 105, Data: 5},
	"melon_stem:6":            {ID: 105, Data: 6},
	"melon_stem:7":            {ID: 105, Data: 7},
	"vine":                    {ID: 106, Data: 0},
	"vine:1":                  {ID: 106, Data: 1},
	"vine:2":                  {ID: 106, Data: 2},
	"vine:4":                  {ID: 106, Data: 4},
	"vine:8":                  {ID: 106, Data: 8},
	"fence_gate":              {ID: 107, Data: 0},
	"fence_gate:1":            {ID: 107, Data: 1},
	"fence_gate:2":            {ID: 107, Data: 2},
	"fence_gate:3":            {ID: 107, Data: 3},
	"fence_gate:4":            {ID: 107, Data: 4},
	"fence_gate:5":            {ID: 107, Data: 5},
	"fence_gate:6":            {ID: 107, Data: 6},
	"fence_gate:7":            {ID: 107, Data: 7},
	"brick_stairs":            {ID: 108, Data: 0},
	"brick_stairs:1":          {ID: 108, Data: 1},
	"brick_stairs:2":          {ID: 108, Data: 2},
	"brick_stairs:3":          {ID: 108, Data: 3},
	"brick_stairs:4":          {ID: 108, Data: 4},
	"brick_stairs:5":          {ID: 108, Data: 5},
	"brick_stairs:6":          {ID: 108, Data: 6},
	"brick_stairs:7":          {ID: 108, Data: 7},
	"stone_brick_stairs":      {ID: 109, Data: 0},
	"stone_brick_stairs:1":    {ID: 109, Data: 1},
	"stone_brick_stairs:2":    {ID: 109, Data: 2},
	"stone_brick_stairs:3":    {ID: 109, Data: 3},
	"stone_brick_stairs:4":    {ID: 109, Data: 4},
	"stone_brick_stairs:5":    {ID: 109, Data: 5},
	"stone_brick_stairs:6":    {ID: 109, Data: 6},
	"stone_brick_stairs:7":    {ID: 109, Data: 7},
	"mycelium":                {ID: 110, Data: 0},
	"waterlily":               {ID: 111, Data: 0},
	"nether_brick":            {ID: 112, Data: 0},
	"nether_brick_fence":      {ID: 113, Data: 0},
	"nether_brick_stairs":     {ID: 114, Data: 0},
	"nether_brick_stairs:1":   {ID: 114, Data: 1},
	"nether_brick_stairs:2":   {ID: 114, Data: 2},
	"nether_brick_stairs:3":   {ID: 114, Data: 3},
	"nether_brick_stairs:4":   {ID: 114, Data: 4},
	"nether_brick_stairs:5":   {ID: 114, Data: 5},
	"nether_brick_stairs:6":   {ID: 114, Data: 6},
	"nether_brick_stairs:7":   {ID: 114, Data: 7},
	//"nether_wart": {ID: 115, Data: 0},
	"nether_wart:1":    {ID: 115, Data: 1},
	"nether_wart:2":    {ID: 115, Data: 2},
	"nether_wart:3":    {ID: 115, Data: 3},
	"enchanting_table": {ID: 116, Data: 0},
	//"brewing_stand": {ID: 117, Data: 0},
	"brewing_stand:1": {ID: 117, Data: 1},
	"brewing_stand:2": {ID: 117, Data: 2},
	"brewing_stand:4": {ID: 117, Data: 4},
	"brewing_stand:5": {ID: 117, Data: 5},
	"brewing_stand:6": {ID: 117, Data: 6},
	"brewing_stand:7": {ID: 117, Data: 7},
	//"cauldron": {ID: 118, Data: 0},
	"cauldron:1":           {ID: 118, Data: 1},
	"cauldron:2":           {ID: 118, Data: 2},
	"cauldron:3":           {ID: 118, Data: 3},
	"end_portal":           {ID: 119, Data: 0},
	"end_portal_frame":     {ID: 120, Data: 0},
	"end_portal_frame:1":   {ID: 120, Data: 1},
	"end_portal_frame:2":   {ID: 120, Data: 2},
	"end_portal_frame:3":   {ID: 120, Data: 3},
	"end_portal_frame:4":   {ID: 120, Data: 4},
	"end_portal_frame:5":   {ID: 120, Data: 5},
	"end_portal_frame:6":   {ID: 120, Data: 6},
	"end_portal_frame:7":   {ID: 120, Data: 7},
	"end_stone":            {ID: 121, Data: 0},
	"dragon_egg":           {ID: 122, Data: 0},
	"redstone_lamp":        {ID: 123, Data: 0},
	"lit_redstone_lamp":    {ID: 124, Data: 0},
	"double_wooden_slab":   {ID: 125, Data: 0},
	"double_wooden_slab:1": {ID: 125, Data: 1},
	"double_wooden_slab:2": {ID: 125, Data: 2},
	"double_wooden_slab:3": {ID: 125, Data: 3},
	"double_wooden_slab:4": {ID: 125, Data: 4},
	"double_wooden_slab:5": {ID: 125, Data: 5},
	"wooden_slab":          {ID: 126, Data: 0},
	"wooden_slab:1":        {ID: 126, Data: 1},
	"wooden_slab:2":        {ID: 126, Data: 2},
	"wooden_slab:3":        {ID: 126, Data: 3},
	"wooden_slab:4":        {ID: 126, Data: 4},
	"wooden_slab:5":        {ID: 126, Data: 5},
	"wooden_slab:8":        {ID: 126, Data: 8},
	"wooden_slab:9":        {ID: 126, Data: 9},
	"wooden_slab:10":       {ID: 126, Data: 10},
	"wooden_slab:11":       {ID: 126, Data: 11},
	"wooden_slab:12":       {ID: 126, Data: 12},
	"wooden_slab:13":       {ID: 126, Data: 13},
	"cocoa":                {ID: 127, Data: 0},
	"sandstone_stairs":     {ID: 128, Data: 0},
	"sandstone_stairs:1":   {ID: 128, Data: 1},
	"sandstone_stairs:2":   {ID: 128, Data: 2},
	"sandstone_stairs:3":   {ID: 128, Data: 3},
	"sandstone_stairs:4":   {ID: 128, Data: 4},
	"sandstone_stairs:5":   {ID: 128, Data: 5},
	"sandstone_stairs:6":   {ID: 128, Data: 6},
	"sandstone_stairs:7":   {ID: 128, Data: 7},
	"emerald_ore":          {ID: 129, Data: 0},
	"ender_chest":          {ID: 130, Data: 0},
	"ender_chest:2":        {ID: 130, Data: 2},
	"ender_chest:3":        {ID: 130, Data: 3},
	"ender_chest:4":        {ID: 130, Data: 4},
	"ender_chest:5":        {ID: 130, Data: 5},
	"tripwire_hook":        {ID: 131, Data: 0},
	"tripwire_hook:1":      {ID: 131, Data: 1},
	"tripwire_hook:2":      {ID: 131, Data: 2},
	"tripwire_hook:3":      {ID: 131, Data: 3},
	"tripwire_hook:4":      {ID: 131, Data: 4},
	"tripwire_hook:5":      {ID: 131, Data: 5},
	"tripwire_hook:6":      {ID: 131, Data: 6},
	"tripwire_hook:7":      {ID: 131, Data: 7},
	"tripwire_hook:8":      {ID: 131, Data: 8},
	"tripwire_hook:9":      {ID: 131, Data: 9},
	"tripwire_hook:10":     {ID: 131, Data: 10},
	"tripwire_hook:11":     {ID: 131, Data: 11},
	"tripwire:2":           {ID: 132, Data: 2},
	"tripwire:3":           {ID: 132, Data: 3},
	"tripwire:6":           {ID: 132, Data: 6},
	"tripwire:7":           {ID: 132, Data: 7},
	"emerald_block":        {ID: 133, Data: 0},
	"spruce_stairs":        {ID: 134, Data: 0},
	"spruce_stairs:1":      {ID: 134, Data: 1},
	"spruce_stairs:2":      {ID: 134, Data: 2},
	"spruce_stairs:3":      {ID: 134, Data: 3},
	"spruce_stairs:4":      {ID: 134, Data: 4},
	"spruce_stairs:5":      {ID: 134, Data: 5},
	"spruce_stairs:6":      {ID: 134, Data: 6},
	"spruce_stairs:7":      {ID: 134, Data: 7},
	"birch_stairs":         {ID: 135, Data: 0},
	"birch_stairs:1":       {ID: 135, Data: 1},
	"birch_stairs:2":       {ID: 135, Data: 2},
	"birch_stairs:3":       {ID: 135, Data: 3},
	"birch_stairs:4":       {ID: 135, Data: 4},
	"birch_stairs:5":       {ID: 135, Data: 5},
	"birch_stairs:6":       {ID: 135, Data: 6},
	"birch_stairs:7":       {ID: 135, Data: 7},
	"jungle_stairs":        {ID: 136, Data: 0},
	"jungle_stairs:1":      {ID: 136, Data: 1},
	"jungle_stairs:2":      {ID: 136, Data: 2},
	"jungle_stairs:3":      {ID: 136, Data: 3},
	"jungle_stairs:4":      {ID: 136, Data: 4},
	"jungle_stairs:5":      {ID: 136, Data: 5},
	"jungle_stairs:6":      {ID: 136, Data: 6},
	"jungle_stairs:7":      {ID: 136, Data: 7},
	"command_block":        {ID: 137, Data: 0},
	"command_block:1":      {ID: 137, Data: 1},
	"command_block:2":      {ID: 137, Data: 2},
	"command_block:3":      {ID: 137, Data: 3},
	"command_block:4":      {ID: 137, Data: 4},
	"command_block:5":      {ID: 137, Data: 5},
	"command_block:8":      {ID: 137, Data: 8},
	"command_block:9":      {ID: 137, Data: 9},
	"command_block:12":     {ID: 137, Data: 12},
	"command_block:13":     {ID: 137, Data: 13},
	"command_block:14":     {ID: 137, Data: 14},
	"command_block:15":     {ID: 137, Data: 15},
	"beacon":               {ID: 138, Data: 0},
	"cobblestone_wall":     {ID: 139, Data: 0},
	"cobblestone_wall:1":   {ID: 139, Data: 1},
	//"flower_pot": {ID: 140, Data: 0},
	"carrots":          {ID: 141, Data: 0},
	"carrots:1":        {ID: 141, Data: 1},
	"carrots:2":        {ID: 141, Data: 2},
	"carrots:3":        {ID: 141, Data: 3},
	"carrots:4":        {ID: 141, Data: 4},
	"carrots:5":        {ID: 141, Data: 5},
	"carrots:6":        {ID: 141, Data: 6},
	"carrots:7":        {ID: 141, Data: 7},
	"potatoes":         {ID: 142, Data: 0},
	"potatoes:1":       {ID: 142, Data: 1},
	"potatoes:2":       {ID: 142, Data: 2},
	"potatoes:3":       {ID: 142, Data: 3},
	"potatoes:4":       {ID: 142, Data: 4},
	"potatoes:5":       {ID: 142, Data: 5},
	"potatoes:6":       {ID: 142, Data: 6},
	"potatoes:7":       {ID: 142, Data: 7},
	"wooden_button":    {ID: 143, Data: 0},
	"wooden_button:1":  {ID: 143, Data: 1},
	"wooden_button:2":  {ID: 143, Data: 2},
	"wooden_button:3":  {ID: 143, Data: 3},
	"wooden_button:4":  {ID: 143, Data: 4},
	"wooden_button:5":  {ID: 143, Data: 5},
	"wooden_button:8":  {ID: 143, Data: 8},
	"wooden_button:9":  {ID: 143, Data: 9},
	"wooden_button:10": {ID: 143, Data: 10},
	"wooden_button:11": {ID: 143, Data: 11},
	"wooden_button:12": {ID: 143, Data: 12},
	"wooden_button:13": {ID: 143, Data: 13},
	//"skull": {ID: 144, Data: 0},
	//"skull:1": {ID: 144, Data: 1},
	//"skull:2": {ID: 144, Data: 2},
	//"skull:3": {ID: 144, Data: 3},
	//"skull:4":                          {ID: 144, Data: 4},
	"anvil":                            {ID: 145, Data: 0},
	"anvil:1":                          {ID: 145, Data: 1},
	"anvil:2":                          {ID: 145, Data: 2},
	"anvil:3":                          {ID: 145, Data: 3},
	"anvil:4":                          {ID: 145, Data: 4},
	"anvil:5":                          {ID: 145, Data: 5},
	"anvil:6":                          {ID: 145, Data: 6},
	"anvil:7":                          {ID: 145, Data: 7},
	"anvil:8":                          {ID: 145, Data: 8},
	"anvil:9":                          {ID: 145, Data: 9},
	"anvil:10":                         {ID: 145, Data: 10},
	"anvil:11":                         {ID: 145, Data: 11},
	"anvil:12":                         {ID: 145, Data: 12},
	"anvil:13":                         {ID: 145, Data: 13},
	"anvil:14":                         {ID: 145, Data: 14},
	"trapped_chest":                    {ID: 146, Data: 0},
	"trapped_chest:2":                  {ID: 146, Data: 2},
	"trapped_chest:3":                  {ID: 146, Data: 3},
	"trapped_chest:4":                  {ID: 146, Data: 4},
	"trapped_chest:5":                  {ID: 146, Data: 5},
	"light_weighted_pressure_plate":    {ID: 147, Data: 0},
	"light_weighted_pressure_plate:1":  {ID: 147, Data: 1},
	"light_weighted_pressure_plate:2":  {ID: 147, Data: 2},
	"light_weighted_pressure_plate:3":  {ID: 147, Data: 3},
	"light_weighted_pressure_plate:4":  {ID: 147, Data: 4},
	"light_weighted_pressure_plate:5":  {ID: 147, Data: 5},
	"light_weighted_pressure_plate:6":  {ID: 147, Data: 6},
	"light_weighted_pressure_plate:7":  {ID: 147, Data: 7},
	"light_weighted_pressure_plate:8":  {ID: 147, Data: 8},
	"light_weighted_pressure_plate:9":  {ID: 147, Data: 9},
	"light_weighted_pressure_plate:10": {ID: 147, Data: 10},
	"light_weighted_pressure_plate:11": {ID: 147, Data: 11},
	"light_weighted_pressure_plate:12": {ID: 147, Data: 12},
	"light_weighted_pressure_plate:13": {ID: 147, Data: 13},
	"light_weighted_pressure_plate:14": {ID: 147, Data: 14},
	"light_weighted_pressure_plate:15": {ID: 147, Data: 15},
	"heavy_weighted_pressure_plate":    {ID: 148, Data: 0},
	"heavy_weighted_pressure_plate:1":  {ID: 148, Data: 1},
	"heavy_weighted_pressure_plate:2":  {ID: 148, Data: 2},
	"heavy_weighted_pressure_plate:3":  {ID: 148, Data: 3},
	"heavy_weighted_pressure_plate:4":  {ID: 148, Data: 4},
	"heavy_weighted_pressure_plate:5":  {ID: 148, Data: 5},
	"heavy_weighted_pressure_plate:6":  {ID: 148, Data: 6},
	"heavy_weighted_pressure_plate:7":  {ID: 148, Data: 7},
	"heavy_weighted_pressure_plate:8":  {ID: 148, Data: 8},
	"heavy_weighted_pressure_plate:9":  {ID: 148, Data: 9},
	"heavy_weighted_pressure_plate:10": {ID: 148, Data: 10},
	"heavy_weighted_pressure_plate:11": {ID: 148, Data: 11},
	"heavy_weighted_pressure_plate:12": {ID: 148, Data: 12},
	"heavy_weighted_pressure_plate:13": {ID: 148, Data: 13},
	"heavy_weighted_pressure_plate:14": {ID: 148, Data: 14},
	"heavy_weighted_pressure_plate:15": {ID: 148, Data: 15},
	"unpowered_comparator":             {ID: 149, Data: 0},
	"unpowered_comparator:1":           {ID: 149, Data: 1},
	"unpowered_comparator:2":           {ID: 149, Data: 2},
	"unpowered_comparator:3":           {ID: 149, Data: 3},
	"unpowered_comparator:4":           {ID: 149, Data: 4},
	"unpowered_comparator:5":           {ID: 149, Data: 5},
	"unpowered_comparator:6":           {ID: 149, Data: 6},
	"unpowered_comparator:7":           {ID: 149, Data: 7},
	"powered_comparator":               {ID: 150, Data: 0},
	"daylight_detector":                {ID: 151, Data: 0},
	"daylight_detector:1":              {ID: 151, Data: 1},
	"daylight_detector:2":              {ID: 151, Data: 2},
	"daylight_detector:3":              {ID: 151, Data: 3},
	"daylight_detector:4":              {ID: 151, Data: 4},
	"daylight_detector:5":              {ID: 151, Data: 5},
	"daylight_detector:6":              {ID: 151, Data: 6},
	"daylight_detector:7":              {ID: 151, Data: 7},
	"daylight_detector:8":              {ID: 151, Data: 8},
	"daylight_detector:9":              {ID: 151, Data: 9},
	"daylight_detector:10":             {ID: 151, Data: 10},
	"daylight_detector:11":             {ID: 151, Data: 11},
	"daylight_detector:12":             {ID: 151, Data: 12},
	"daylight_detector:13":             {ID: 151, Data: 13},
	"daylight_detector:14":             {ID: 151, Data: 14},
	"daylight_detector:15":             {ID: 151, Data: 15},
	"redstone_block":                   {ID: 152, Data: 0},
	"quartz_ore":                       {ID: 153, Data: 0},
	"hopper":                           {ID: 154, Data: 0},
	"hopper:2":                         {ID: 154, Data: 2},
	"hopper:3":                         {ID: 154, Data: 3},
	"hopper:4":                         {ID: 154, Data: 4},
	"hopper:5":                         {ID: 154, Data: 5},
	"quartz_block":                     {ID: 155, Data: 0},
	"quartz_block:1":                   {ID: 155, Data: 1},
	"quartz_block:2":                   {ID: 155, Data: 2},
	"quartz_block:3":                   {ID: 155, Data: 3},
	"quartz_block:4":                   {ID: 155, Data: 4},
	"quartz_stairs":                    {ID: 156, Data: 0},
	"quartz_stairs:1":                  {ID: 156, Data: 1},
	"quartz_stairs:2":                  {ID: 156, Data: 2},
	"quartz_stairs:3":                  {ID: 156, Data: 3},
	"quartz_stairs:4":                  {ID: 156, Data: 4},
	"quartz_stairs:5":                  {ID: 156, Data: 5},
	"quartz_stairs:6":                  {ID: 156, Data: 6},
	"quartz_stairs:7":                  {ID: 156, Data: 7},
	"activator_rail":                   {ID: 157, Data: 0},
	"activator_rail:1":                 {ID: 157, Data: 1},
	"activator_rail:2":                 {ID: 157, Data: 2},
	"activator_rail:3":                 {ID: 157, Data: 3},
	"activator_rail:4":                 {ID: 157, Data: 4},
	"activator_rail:5":                 {ID: 157, Data: 5},
	"activator_rail:8":                 {ID: 157, Data: 8},
	"activator_rail:9":                 {ID: 157, Data: 9},
	"activator_rail:10":                {ID: 157, Data: 10},
	"activator_rail:11":                {ID: 157, Data: 11},
	"activator_rail:12":                {ID: 157, Data: 12},
	"activator_rail:13":                {ID: 157, Data: 13},
	"dropper":                          {ID: 158, Data: 0},
	"dropper:1":                        {ID: 158, Data: 1},
	"dropper:2":                        {ID: 158, Data: 2},
	"dropper:3":                        {ID: 158, Data: 3},
	"dropper:4":                        {ID: 158, Data: 4},
	"dropper:5":                        {ID: 158, Data: 5},
	"stained_hardened_clay":            {ID: 159, Data: 0},
	"stained_hardened_clay:1":          {ID: 159, Data: 1},
	"stained_hardened_clay:2":          {ID: 159, Data: 2},
	"stained_hardened_clay:3":          {ID: 159, Data: 3},
	"stained_hardened_clay:4":          {ID: 159, Data: 4},
	"stained_hardened_clay:5":          {ID: 159, Data: 5},
	"stained_hardened_clay:6":          {ID: 159, Data: 6},
	"stained_hardened_clay:7":          {ID: 159, Data: 7},
	"stained_hardened_clay:8":          {ID: 159, Data: 8},
	"stained_hardened_clay:9":          {ID: 159, Data: 9},
	"stained_hardened_clay:10":         {ID: 159, Data: 10},
	"stained_hardened_clay:11":         {ID: 159, Data: 11},
	"stained_hardened_clay:12":         {ID: 159, Data: 12},
	"stained_hardened_clay:13":         {ID: 159, Data: 13},
	"stained_hardened_clay:14":         {ID: 159, Data: 14},
	"stained_hardened_clay:15":         {ID: 159, Data: 15},
	"stained_glass_pane":               {ID: 160, Data: 0},
	"stained_glass_pane:1":             {ID: 160, Data: 1},
	"stained_glass_pane:2":             {ID: 160, Data: 2},
	"stained_glass_pane:3":             {ID: 160, Data: 3},
	"stained_glass_pane:4":             {ID: 160, Data: 4},
	"stained_glass_pane:5":             {ID: 160, Data: 5},
	"stained_glass_pane:6":             {ID: 160, Data: 6},
	"stained_glass_pane:7":             {ID: 160, Data: 7},
	"stained_glass_pane:8":             {ID: 160, Data: 8},
	"stained_glass_pane:9":             {ID: 160, Data: 9},
	"stained_glass_pane:10":            {ID: 160, Data: 10},
	"stained_glass_pane:11":            {ID: 160, Data: 11},
	"stained_glass_pane:12":            {ID: 160, Data: 12},
	"stained_glass_pane:13":            {ID: 160, Data: 13},
	"stained_glass_pane:14":            {ID: 160, Data: 14},
	"stained_glass_pane:15":            {ID: 160, Data: 15},
	"leaves2":                          {ID: 161, Data: 0},
	"leaves2:1":                        {ID: 161, Data: 1},
	"leaves2:4":                        {ID: 161, Data: 4},
	"leaves2:5":                        {ID: 161, Data: 5},
	"leaves2:8":                        {ID: 161, Data: 8},
	"leaves2:9":                        {ID: 161, Data: 9},
	"leaves2:12":                       {ID: 161, Data: 12},
	"leaves2:13":                       {ID: 161, Data: 13},
	"log2":                             {ID: 162, Data: 0},
	"log2:1":                           {ID: 162, Data: 1},
	"log2:4":                           {ID: 162, Data: 4},
	"log2:5":                           {ID: 162, Data: 5},
	"log2:8":                           {ID: 162, Data: 8},
	"log2:9":                           {ID: 162, Data: 9},
	"acacia_stairs":                    {ID: 163, Data: 0},
	"acacia_stairs:1":                  {ID: 163, Data: 1},
	"acacia_stairs:2":                  {ID: 163, Data: 2},
	"acacia_stairs:3":                  {ID: 163, Data: 3},
	"acacia_stairs:4":                  {ID: 163, Data: 4},
	"acacia_stairs:5":                  {ID: 163, Data: 5},
	"acacia_stairs:6":                  {ID: 163, Data: 6},
	"acacia_stairs:7":                  {ID: 163, Data: 7},
	"dark_oak_stairs":                  {ID: 164, Data: 0},
	"dark_oak_stairs:1":                {ID: 164, Data: 1},
	"dark_oak_stairs:2":                {ID: 164, Data: 2},
	"dark_oak_stairs:3":                {ID: 164, Data: 3},
	"dark_oak_stairs:4":                {ID: 164, Data: 4},
	"dark_oak_stairs:5":                {ID: 164, Data: 5},
	"dark_oak_stairs:6":                {ID: 164, Data: 6},
	"dark_oak_stairs:7":                {ID: 164, Data: 7},
	"slime":                            {ID: 165, Data: 0},
	"barrier":                          {ID: 166, Data: 0},
	"iron_trapdoor":                    {ID: 167, Data: 0},
	"iron_trapdoor:1":                  {ID: 167, Data: 1},
	"iron_trapdoor:2":                  {ID: 167, Data: 2},
	"iron_trapdoor:3":                  {ID: 167, Data: 3},
	"iron_trapdoor:4":                  {ID: 167, Data: 4},
	"iron_trapdoor:5":                  {ID: 167, Data: 5},
	"iron_trapdoor:6":                  {ID: 167, Data: 6},
	"iron_trapdoor:7":                  {ID: 167, Data: 7},
	"iron_trapdoor:8":                  {ID: 167, Data: 8},
	"iron_trapdoor:9":                  {ID: 167, Data: 9},
	"iron_trapdoor:10":                 {ID: 167, Data: 10},
	"iron_trapdoor:11":                 {ID: 167, Data: 11},
	"iron_trapdoor:12":                 {ID: 167, Data: 12},
	"iron_trapdoor:13":                 {ID: 167, Data: 13},
	"iron_trapdoor:14":                 {ID: 167, Data: 14},
	"iron_trapdoor:15":                 {ID: 167, Data: 15},
	"prismarine":                       {ID: 168, Data: 0},
	"prismarine:1":                     {ID: 168, Data: 1},
	"prismarine:2":                     {ID: 168, Data: 2},
	"sea_lantern":                      {ID: 169, Data: 0},
	"hay_block":                        {ID: 170, Data: 0},
	"hay_block:4":                      {ID: 170, Data: 4},
	"hay_block:8":                      {ID: 170, Data: 8},
	"carpet":                           {ID: 171, Data: 0},
	"carpet:1":                         {ID: 171, Data: 1},
	"carpet:2":                         {ID: 171, Data: 2},
	"carpet:3":                         {ID: 171, Data: 3},
	"carpet:4":                         {ID: 171, Data: 4},
	"carpet:5":                         {ID: 171, Data: 5},
	"carpet:6":                         {ID: 171, Data: 6},
	"carpet:7":                         {ID: 171, Data: 7},
	"carpet:8":                         {ID: 171, Data: 8},
	"carpet:9":                         {ID: 171, Data: 9},
	"carpet:10":                        {ID: 171, Data: 10},
	"carpet:11":                        {ID: 171, Data: 11},
	"carpet:12":                        {ID: 171, Data: 12},
	"carpet:13":                        {ID: 171, Data: 13},
	"carpet:14":                        {ID: 171, Data: 14},
	"carpet:15":                        {ID: 171, Data: 15},
	"hardened_clay":                    {ID: 172, Data: 0},
	"hardened_clay:1":                  {ID: 172, Data: 1},
	"hardened_clay:2":                  {ID: 172, Data: 2},
	"hardened_clay:3":                  {ID: 172, Data: 3},
	"hardened_clay:4":                  {ID: 172, Data: 4},
	"hardened_clay:5":                  {ID: 172, Data: 5},
	"hardened_clay:6":                  {ID: 172, Data: 6},
	"hardened_clay:7":                  {ID: 172, Data: 7},
	"hardened_clay:8":                  {ID: 172, Data: 8},
	"hardened_clay:9":                  {ID: 172, Data: 9},
	"hardened_clay:10":                 {ID: 172, Data: 10},
	"hardened_clay:11":                 {ID: 172, Data: 11},
	"hardened_clay:12":                 {ID: 172, Data: 12},
	"hardened_clay:13":                 {ID: 172, Data: 13},
	"hardened_clay:14":                 {ID: 172, Data: 14},
	"hardened_clay:15":                 {ID: 172, Data: 15},
	"coal_block":                       {ID: 173, Data: 0},
	"packed_ice":                       {ID: 174, Data: 0},
	"double_plant":                     {ID: 175, Data: 0},
	"double_plant:1":                   {ID: 175, Data: 1},
	"double_plant:2":                   {ID: 175, Data: 2},
	"double_plant:3":                   {ID: 175, Data: 3},
	"double_plant:4":                   {ID: 175, Data: 4},
	"double_plant:5":                   {ID: 175, Data: 5},
	"double_plant:8":                   {ID: 175, Data: 8},
	"standing_banner":                  {ID: 176, Data: 0},
	"standing_banner:1":                {ID: 176, Data: 1},
	"standing_banner:2":                {ID: 176, Data: 2},
	"standing_banner:3":                {ID: 176, Data: 3},
	"standing_banner:4":                {ID: 176, Data: 4},
	"standing_banner:5":                {ID: 176, Data: 5},
	"standing_banner:6":                {ID: 176, Data: 6},
	"standing_banner:7":                {ID: 176, Data: 7},
	"standing_banner:8":                {ID: 176, Data: 8},
	"standing_banner:9":                {ID: 176, Data: 9},
	"standing_banner:10":               {ID: 176, Data: 10},
	"standing_banner:11":               {ID: 176, Data: 11},
	"standing_banner:12":               {ID: 176, Data: 12},
	"standing_banner:13":               {ID: 176, Data: 13},
	"standing_banner:14":               {ID: 176, Data: 14},
	"standing_banner:15":               {ID: 176, Data: 15},
	"wall_banner:2":                    {ID: 177, Data: 2},
	"wall_banner:3":                    {ID: 177, Data: 3},
	"wall_banner:4":                    {ID: 177, Data: 4},
	"wall_banner:5":                    {ID: 177, Data: 5},
	"daylight_detector_inverted":       {ID: 178, Data: 0},
	"daylight_detector_inverted:1":     {ID: 178, Data: 1},
	"daylight_detector_inverted:2":     {ID: 178, Data: 2},
	"daylight_detector_inverted:3":     {ID: 178, Data: 3},
	"daylight_detector_inverted:4":     {ID: 178, Data: 4},
	"daylight_detector_inverted:5":     {ID: 178, Data: 5},
	"daylight_detector_inverted:6":     {ID: 178, Data: 6},
	"daylight_detector_inverted:7":     {ID: 178, Data: 7},
	"daylight_detector_inverted:8":     {ID: 178, Data: 8},
	"daylight_detector_inverted:9":     {ID: 178, Data: 9},
	"daylight_detector_inverted:10":    {ID: 178, Data: 10},
	"daylight_detector_inverted:11":    {ID: 178, Data: 11},
	"daylight_detector_inverted:12":    {ID: 178, Data: 12},
	"daylight_detector_inverted:13":    {ID: 178, Data: 13},
	"daylight_detector_inverted:14":    {ID: 178, Data: 14},
	"daylight_detector_inverted:15":    {ID: 178, Data: 15},
	"red_sandstone":                    {ID: 179, Data: 0},
	"red_sandstone:1":                  {ID: 179, Data: 1},
	"red_sandstone:2":                  {ID: 179, Data: 2},
	"red_sandstone_stairs":             {ID: 180, Data: 0},
	"red_sandstone_stairs:1":           {ID: 180, Data: 1},
	"red_sandstone_stairs:2":           {ID: 180, Data: 2},
	"red_sandstone_stairs:3":           {ID: 180, Data: 3},
	"red_sandstone_stairs:4":           {ID: 180, Data: 4},
	"red_sandstone_stairs:5":           {ID: 180, Data: 5},
	"red_sandstone_stairs:6":           {ID: 180, Data: 6},
	"red_sandstone_stairs:7":           {ID: 180, Data: 7},
	"double_stone_slab2":               {ID: 181, Data: 0},
	"double_stone_slab2:8":             {ID: 181, Data: 8},
	"stone_slab2":                      {ID: 182, Data: 0},
	"stone_slab2:8":                    {ID: 182, Data: 8},
	"spruce_fence_gate":                {ID: 183, Data: 0},
	"birch_fence_gate":                 {ID: 184, Data: 0},
	"jungle_fence_gate":                {ID: 185, Data: 0},
	"dark_oak_fence_gate":              {ID: 186, Data: 0},
	"acacia_fence_gate":                {ID: 187, Data: 0},
	"spruce_fence":                     {ID: 188, Data: 0},
	"birch_fence":                      {ID: 189, Data: 0},
	"jungle_fence":                     {ID: 190, Data: 0},
	"dark_oak_fence":                   {ID: 191, Data: 0},
	"acacia_fence":                     {ID: 192, Data: 0},
	//"spruce_door":                      {ID: 193, Data: 0},
	"spruce_door:1": {ID: 193, Data: 1},
	"spruce_door:2": {ID: 193, Data: 2},
	"spruce_door:3": {ID: 193, Data: 3},
	"spruce_door:4": {ID: 193, Data: 4},
	"spruce_door:5": {ID: 193, Data: 5},
	"spruce_door:6": {ID: 193, Data: 6},
	"spruce_door:7": {ID: 193, Data: 7},
	"spruce_door:8": {ID: 193, Data: 8},
	"spruce_door:9": {ID: 193, Data: 9},
	//"birch_door":                       {ID: 194, Data: 0},
	"birch_door:1": {ID: 194, Data: 1},
	"birch_door:2": {ID: 194, Data: 2},
	"birch_door:3": {ID: 194, Data: 3},
	"birch_door:4": {ID: 194, Data: 4},
	"birch_door:5": {ID: 194, Data: 5},
	"birch_door:6": {ID: 194, Data: 6},
	"birch_door:7": {ID: 194, Data: 7},
	"birch_door:8": {ID: 194, Data: 8},
	"birch_door:9": {ID: 194, Data: 9},
	//"jungle_door":                      {ID: 195, Data: 0},
	"jungle_door:1": {ID: 195, Data: 1},
	"jungle_door:2": {ID: 195, Data: 2},
	"jungle_door:3": {ID: 195, Data: 3},
	"jungle_door:4": {ID: 195, Data: 4},
	"jungle_door:5": {ID: 195, Data: 5},
	"jungle_door:6": {ID: 195, Data: 6},
	"jungle_door:7": {ID: 195, Data: 7},
	"jungle_door:8": {ID: 195, Data: 8},
	"jungle_door:9": {ID: 195, Data: 9},
	//"acacia_door":                      {ID: 196, Data: 0},
	"acacia_door:1": {ID: 196, Data: 1},
	"acacia_door:2": {ID: 196, Data: 2},
	"acacia_door:3": {ID: 196, Data: 3},
	"acacia_door:4": {ID: 196, Data: 4},
	"acacia_door:5": {ID: 196, Data: 5},
	"acacia_door:6": {ID: 196, Data: 6},
	"acacia_door:7": {ID: 196, Data: 7},
	"acacia_door:8": {ID: 196, Data: 8},
	"acacia_door:9": {ID: 196, Data: 9},
	//"dark_oak_door":                    {ID: 197, Data: 0},
	"dark_oak_door:1":                {ID: 197, Data: 1},
	"dark_oak_door:2":                {ID: 197, Data: 2},
	"dark_oak_door:3":                {ID: 197, Data: 3},
	"dark_oak_door:4":                {ID: 197, Data: 4},
	"dark_oak_door:5":                {ID: 197, Data: 5},
	"dark_oak_door:6":                {ID: 197, Data: 6},
	"dark_oak_door:7":                {ID: 197, Data: 7},
	"dark_oak_door:8":                {ID: 197, Data: 8},
	"dark_oak_door:9":                {ID: 197, Data: 9},
	"end_rod":                        {ID: 198, Data: 0},
	"end_rod:1":                      {ID: 198, Data: 1},
	"end_rod:2":                      {ID: 198, Data: 2},
	"end_rod:3":                      {ID: 198, Data: 3},
	"end_rod:4":                      {ID: 198, Data: 4},
	"end_rod:5":                      {ID: 198, Data: 5},
	"chorus_plant":                   {ID: 199, Data: 0},
	"chorus_flower":                  {ID: 200, Data: 0},
	"chorus_flower:1":                {ID: 200, Data: 1},
	"chorus_flower:2":                {ID: 200, Data: 2},
	"chorus_flower:3":                {ID: 200, Data: 3},
	"chorus_flower:4":                {ID: 200, Data: 4},
	"chorus_flower:5":                {ID: 200, Data: 5},
	"purpur_block":                   {ID: 201, Data: 0},
	"purpur_pillar":                  {ID: 202, Data: 0},
	"purpur_pillar:4":                {ID: 202, Data: 4},
	"purpur_pillar:8":                {ID: 202, Data: 8},
	"purpur_stairs":                  {ID: 203, Data: 0},
	"purpur_stairs:1":                {ID: 203, Data: 1},
	"purpur_stairs:2":                {ID: 203, Data: 2},
	"purpur_stairs:3":                {ID: 203, Data: 3},
	"purpur_stairs:4":                {ID: 203, Data: 4},
	"purpur_stairs:5":                {ID: 203, Data: 5},
	"purpur_stairs:6":                {ID: 203, Data: 6},
	"purpur_stairs:7":                {ID: 203, Data: 7},
	"purpur_double_slab":             {ID: 204, Data: 0},
	"purpur_slab":                    {ID: 205, Data: 0},
	"purpur_slab:8":                  {ID: 205, Data: 8},
	"end_bricks":                     {ID: 206, Data: 0},
	"beetroots":                      {ID: 207, Data: 0},
	"beetroots:1":                    {ID: 207, Data: 1},
	"beetroots:2":                    {ID: 207, Data: 2},
	"beetroots:3":                    {ID: 207, Data: 3},
	"grass_path":                     {ID: 208, Data: 0},
	"end_gateway":                    {ID: 209, Data: 0},
	"repeating_command_block":        {ID: 210, Data: 0},
	"repeating_command_block:1":      {ID: 210, Data: 1},
	"repeating_command_block:2":      {ID: 210, Data: 2},
	"repeating_command_block:3":      {ID: 210, Data: 3},
	"repeating_command_block:4":      {ID: 210, Data: 4},
	"repeating_command_block:5":      {ID: 210, Data: 5},
	"repeating_command_block:8":      {ID: 210, Data: 8},
	"repeating_command_block:9":      {ID: 210, Data: 9},
	"repeating_command_block:12":     {ID: 210, Data: 12},
	"repeating_command_block:13":     {ID: 210, Data: 13},
	"repeating_command_block:14":     {ID: 210, Data: 14},
	"repeating_command_block:15":     {ID: 210, Data: 15},
	"chain_command_block":            {ID: 211, Data: 0},
	"chain_command_block:1":          {ID: 211, Data: 1},
	"chain_command_block:2":          {ID: 211, Data: 2},
	"chain_command_block:3":          {ID: 211, Data: 3},
	"chain_command_block:4":          {ID: 211, Data: 4},
	"chain_command_block:5":          {ID: 211, Data: 5},
	"chain_command_block:8":          {ID: 211, Data: 8},
	"chain_command_block:9":          {ID: 211, Data: 9},
	"chain_command_block:12":         {ID: 211, Data: 12},
	"chain_command_block:13":         {ID: 211, Data: 13},
	"chain_command_block:14":         {ID: 211, Data: 14},
	"chain_command_block:15":         {ID: 211, Data: 15},
	"frosted_ice":                    {ID: 212, Data: 0},
	"magma":                          {ID: 213, Data: 0},
	"nether_wart_block":              {ID: 214, Data: 0},
	"red_nether_brick":               {ID: 215, Data: 0},
	"bone_block":                     {ID: 216, Data: 0},
	"bone_block:4":                   {ID: 216, Data: 4},
	"bone_block:8":                   {ID: 216, Data: 8},
	"structure_void":                 {ID: 217, Data: 0},
	"structure_void:1":               {ID: 217, Data: 1},
	"structure_void:2":               {ID: 217, Data: 2},
	"structure_void:3":               {ID: 217, Data: 3},
	"observer":                       {ID: 218, Data: 0},
	"observer:1":                     {ID: 218, Data: 1},
	"observer:2":                     {ID: 218, Data: 2},
	"observer:3":                     {ID: 218, Data: 3},
	"observer:4":                     {ID: 218, Data: 4},
	"observer:5":                     {ID: 218, Data: 5},
	"white_shulker_box":              {ID: 219, Data: 0},
	"white_shulker_box:1":            {ID: 219, Data: 1},
	"white_shulker_box:2":            {ID: 219, Data: 2},
	"white_shulker_box:3":            {ID: 219, Data: 3},
	"white_shulker_box:4":            {ID: 219, Data: 4},
	"white_shulker_box:5":            {ID: 219, Data: 5},
	"orange_shulker_box":             {ID: 220, Data: 0},
	"orange_shulker_box:1":           {ID: 220, Data: 1},
	"orange_shulker_box:2":           {ID: 220, Data: 2},
	"orange_shulker_box:3":           {ID: 220, Data: 3},
	"orange_shulker_box:4":           {ID: 220, Data: 4},
	"orange_shulker_box:5":           {ID: 220, Data: 5},
	"magenta_shulker_box":            {ID: 221, Data: 0},
	"magenta_shulker_box:1":          {ID: 221, Data: 1},
	"magenta_shulker_box:2":          {ID: 221, Data: 2},
	"magenta_shulker_box:3":          {ID: 221, Data: 3},
	"magenta_shulker_box:4":          {ID: 221, Data: 4},
	"magenta_shulker_box:5":          {ID: 221, Data: 5},
	"light_blue_shulker_box":         {ID: 222, Data: 0},
	"light_blue_shulker_box:1":       {ID: 222, Data: 1},
	"light_blue_shulker_box:2":       {ID: 222, Data: 2},
	"light_blue_shulker_box:3":       {ID: 222, Data: 3},
	"light_blue_shulker_box:4":       {ID: 222, Data: 4},
	"light_blue_shulker_box:5":       {ID: 222, Data: 5},
	"yellow_shulker_box":             {ID: 223, Data: 0},
	"yellow_shulker_box:1":           {ID: 223, Data: 1},
	"yellow_shulker_box:2":           {ID: 223, Data: 2},
	"yellow_shulker_box:3":           {ID: 223, Data: 3},
	"yellow_shulker_box:4":           {ID: 223, Data: 4},
	"yellow_shulker_box:5":           {ID: 223, Data: 5},
	"lime_shulker_box":               {ID: 224, Data: 0},
	"lime_shulker_box:1":             {ID: 224, Data: 1},
	"lime_shulker_box:2":             {ID: 224, Data: 2},
	"lime_shulker_box:3":             {ID: 224, Data: 3},
	"lime_shulker_box:4":             {ID: 224, Data: 4},
	"lime_shulker_box:5":             {ID: 224, Data: 5},
	"pink_shulker_box":               {ID: 225, Data: 0},
	"pink_shulker_box:1":             {ID: 225, Data: 1},
	"pink_shulker_box:2":             {ID: 225, Data: 2},
	"pink_shulker_box:3":             {ID: 225, Data: 3},
	"pink_shulker_box:4":             {ID: 225, Data: 4},
	"pink_shulker_box:5":             {ID: 225, Data: 5},
	"gray_shulker_box":               {ID: 226, Data: 0},
	"gray_shulker_box:1":             {ID: 226, Data: 1},
	"gray_shulker_box:2":             {ID: 226, Data: 2},
	"gray_shulker_box:3":             {ID: 226, Data: 3},
	"gray_shulker_box:4":             {ID: 226, Data: 4},
	"gray_shulker_box:5":             {ID: 226, Data: 5},
	"light_gray_shulker_box":         {ID: 227, Data: 0},
	"light_gray_shulker_box:1":       {ID: 227, Data: 1},
	"light_gray_shulker_box:2":       {ID: 227, Data: 2},
	"light_gray_shulker_box:3":       {ID: 227, Data: 3},
	"light_gray_shulker_box:4":       {ID: 227, Data: 4},
	"light_gray_shulker_box:5":       {ID: 227, Data: 5},
	"cyan_shulker_box":               {ID: 228, Data: 0},
	"cyan_shulker_box:1":             {ID: 228, Data: 1},
	"cyan_shulker_box:2":             {ID: 228, Data: 2},
	"cyan_shulker_box:3":             {ID: 228, Data: 3},
	"cyan_shulker_box:4":             {ID: 228, Data: 4},
	"cyan_shulker_box:5":             {ID: 228, Data: 5},
	"purple_shulker_box":             {ID: 229, Data: 0},
	"purple_shulker_box:1":           {ID: 229, Data: 1},
	"purple_shulker_box:2":           {ID: 229, Data: 2},
	"purple_shulker_box:3":           {ID: 229, Data: 3},
	"purple_shulker_box:4":           {ID: 229, Data: 4},
	"purple_shulker_box:5":           {ID: 229, Data: 5},
	"blue_shulker_box":               {ID: 230, Data: 0},
	"blue_shulker_box:1":             {ID: 230, Data: 1},
	"blue_shulker_box:2":             {ID: 230, Data: 2},
	"blue_shulker_box:3":             {ID: 230, Data: 3},
	"blue_shulker_box:4":             {ID: 230, Data: 4},
	"blue_shulker_box:5":             {ID: 230, Data: 5},
	"brown_shulker_box":              {ID: 231, Data: 0},
	"brown_shulker_box:1":            {ID: 231, Data: 1},
	"brown_shulker_box:2":            {ID: 231, Data: 2},
	"brown_shulker_box:3":            {ID: 231, Data: 3},
	"brown_shulker_box:4":            {ID: 231, Data: 4},
	"brown_shulker_box:5":            {ID: 231, Data: 5},
	"green_shulker_box":              {ID: 232, Data: 0},
	"green_shulker_box:1":            {ID: 232, Data: 1},
	"green_shulker_box:2":            {ID: 232, Data: 2},
	"green_shulker_box:3":            {ID: 232, Data: 3},
	"green_shulker_box:4":            {ID: 232, Data: 4},
	"green_shulker_box:5":            {ID: 232, Data: 5},
	"red_shulker_box":                {ID: 233, Data: 0},
	"red_shulker_box:1":              {ID: 233, Data: 1},
	"red_shulker_box:2":              {ID: 233, Data: 2},
	"red_shulker_box:3":              {ID: 233, Data: 3},
	"red_shulker_box:4":              {ID: 233, Data: 4},
	"red_shulker_box:5":              {ID: 233, Data: 5},
	"black_shulker_box":              {ID: 234, Data: 0},
	"black_shulker_box:1":            {ID: 234, Data: 1},
	"black_shulker_box:2":            {ID: 234, Data: 2},
	"black_shulker_box:3":            {ID: 234, Data: 3},
	"black_shulker_box:4":            {ID: 234, Data: 4},
	"black_shulker_box:5":            {ID: 234, Data: 5},
	"white_glazed_terracotta":        {ID: 235, Data: 0},
	"white_glazed_terracotta:1":      {ID: 235, Data: 1},
	"white_glazed_terracotta:2":      {ID: 235, Data: 2},
	"white_glazed_terracotta:3":      {ID: 235, Data: 3},
	"orange_glazed_terracotta":       {ID: 236, Data: 0},
	"orange_glazed_terracotta:1":     {ID: 236, Data: 1},
	"orange_glazed_terracotta:2":     {ID: 236, Data: 2},
	"orange_glazed_terracotta:3":     {ID: 236, Data: 3},
	"magenta_glazed_terracotta":      {ID: 237, Data: 0},
	"magenta_glazed_terracotta:1":    {ID: 237, Data: 1},
	"magenta_glazed_terracotta:2":    {ID: 237, Data: 2},
	"magenta_glazed_terracotta:3":    {ID: 237, Data: 3},
	"light_blue_glazed_terracotta":   {ID: 238, Data: 0},
	"light_blue_glazed_terracotta:1": {ID: 238, Data: 1},
	"light_blue_glazed_terracotta:2": {ID: 238, Data: 2},
	"light_blue_glazed_terracotta:3": {ID: 238, Data: 3},
	"yellow_glazed_terracotta":       {ID: 239, Data: 0},
	"yellow_glazed_terracotta:1":     {ID: 239, Data: 1},
	"yellow_glazed_terracotta:2":     {ID: 239, Data: 2},
	"yellow_glazed_terracotta:3":     {ID: 239, Data: 3},
	"lime_glazed_terracotta":         {ID: 240, Data: 0},
	"lime_glazed_terracotta:1":       {ID: 240, Data: 1},
	"lime_glazed_terracotta:2":       {ID: 240, Data: 2},
	"lime_glazed_terracotta:3":       {ID: 240, Data: 3},
	"pink_glazed_terracotta":         {ID: 241, Data: 0},
	"pink_glazed_terracotta:1":       {ID: 241, Data: 1},
	"pink_glazed_terracotta:2":       {ID: 241, Data: 2},
	"pink_glazed_terracotta:3":       {ID: 241, Data: 3},
	"gray_glazed_terracotta":         {ID: 242, Data: 0},
	"gray_glazed_terracotta:1":       {ID: 242, Data: 1},
	"gray_glazed_terracotta:2":       {ID: 242, Data: 2},
	"gray_glazed_terracotta:3":       {ID: 242, Data: 3},
	"light_gray_glazed_terracotta":   {ID: 243, Data: 0},
	"light_gray_glazed_terracotta:1": {ID: 243, Data: 1},
	"light_gray_glazed_terracotta:2": {ID: 243, Data: 2},
	"light_gray_glazed_terracotta:3": {ID: 243, Data: 3},
	"cyan_glazed_terracotta":         {ID: 244, Data: 0},
	"cyan_glazed_terracotta:1":       {ID: 244, Data: 1},
	"cyan_glazed_terracotta:2":       {ID: 244, Data: 2},
	"cyan_glazed_terracotta:3":       {ID: 244, Data: 3},
	"purple_glazed_terracotta":       {ID: 245, Data: 0},
	"purple_glazed_terracotta:1":     {ID: 245, Data: 1},
	"purple_glazed_terracotta:2":     {ID: 245, Data: 2},
	"purple_glazed_terracotta:3":     {ID: 245, Data: 3},
	"blue_glazed_terracotta":         {ID: 246, Data: 0},
	"blue_glazed_terracotta:1":       {ID: 246, Data: 1},
	"blue_glazed_terracotta:2":       {ID: 246, Data: 2},
	"blue_glazed_terracotta:3":       {ID: 246, Data: 3},
	"brown_glazed_terracotta":        {ID: 247, Data: 0},
	"brown_glazed_terracotta:1":      {ID: 247, Data: 1},
	"brown_glazed_terracotta:2":      {ID: 247, Data: 2},
	"brown_glazed_terracotta:3":      {ID: 247, Data: 3},
	"green_glazed_terracotta":        {ID: 248, Data: 0},
	"green_glazed_terracotta:1":      {ID: 248, Data: 1},
	"green_glazed_terracotta:2":      {ID: 248, Data: 2},
	"green_glazed_terracotta:3":      {ID: 248, Data: 3},
	"red_glazed_terracotta":          {ID: 249, Data: 0},
	"red_glazed_terracotta:1":        {ID: 249, Data: 1},
	"red_glazed_terracotta:2":        {ID: 249, Data: 2},
	"red_glazed_terracotta:3":        {ID: 249, Data: 3},
	"black_glazed_terracotta":        {ID: 250, Data: 0},
	"black_glazed_terracotta:1":      {ID: 250, Data: 1},
	"black_glazed_terracotta:2":      {ID: 250, Data: 2},
	"black_glazed_terracotta:3":      {ID: 250, Data: 3},
	"concrete":                       {ID: 251, Data: 0},
	"concrete:1":                     {ID: 251, Data: 1},
	"concrete:2":                     {ID: 251, Data: 2},
	"concrete:3":                     {ID: 251, Data: 3},
	"concrete:4":                     {ID: 251, Data: 4},
	"concrete:5":                     {ID: 251, Data: 5},
	"concrete:6":                     {ID: 251, Data: 6},
	"concrete:7":                     {ID: 251, Data: 7},
	"concrete:8":                     {ID: 251, Data: 8},
	"concrete:9":                     {ID: 251, Data: 9},
	"concrete:10":                    {ID: 251, Data: 10},
	"concrete:11":                    {ID: 251, Data: 11},
	"concrete:12":                    {ID: 251, Data: 12},
	"concrete:13":                    {ID: 251, Data: 13},
	"concrete:14":                    {ID: 251, Data: 14},
	"concrete:15":                    {ID: 251, Data: 15},
	"concrete_powder":                {ID: 252, Data: 0},
	"concrete_powder:1":              {ID: 252, Data: 1},
	"concrete_powder:2":              {ID: 252, Data: 2},
	"concrete_powder:3":              {ID: 252, Data: 3},
	"concrete_powder:4":              {ID: 252, Data: 4},
	"concrete_powder:5":              {ID: 252, Data: 5},
	"concrete_powder:6":              {ID: 252, Data: 6},
	"concrete_powder:7":              {ID: 252, Data: 7},
	"concrete_powder:8":              {ID: 252, Data: 8},
	"concrete_powder:9":              {ID: 252, Data: 9},
	"concrete_powder:10":             {ID: 252, Data: 10},
	"concrete_powder:11":             {ID: 252, Data: 11},
	"concrete_powder:12":             {ID: 252, Data: 12},
	"concrete_powder:13":             {ID: 252, Data: 13},
	"concrete_powder:14":             {ID: 252, Data: 14},
	"concrete_powder:15":             {ID: 252, Data: 15},
	"structure_block":                {ID: 255, Data: 0},
	"structure_block:1":              {ID: 255, Data: 1},
	"structure_block:2":              {ID: 255, Data: 2},
	"structure_block:3":              {ID: 255, Data: 3},
	"iron_shovel":                    {ID: 256, Data: 0},
	"iron_pickaxe":                   {ID: 257, Data: 0},
	"iron_axe":                       {ID: 258, Data: 0},
	"flint_and_steel":                {ID: 259, Data: 0},
	"apple":                          {ID: 260, Data: 0},
	"bow":                            {ID: 261, Data: 0},
	"arrow":                          {ID: 262, Data: 0},
	"coal":                           {ID: 263, Data: 0},
	"coal:1":                         {ID: 263, Data: 1},
	"diamond":                        {ID: 264, Data: 0},
	"iron_ingot":                     {ID: 265, Data: 0},
	"gold_ingot":                     {ID: 266, Data: 0},
	"iron_sword":                     {ID: 267, Data: 0},
	"wooden_sword":                   {ID: 268, Data: 0},
	"wooden_shovel":                  {ID: 269, Data: 0},
	"wooden_pickaxe":                 {ID: 270, Data: 0},
	"wooden_axe":                     {ID: 271, Data: 0},
	"stone_sword":                    {ID: 272, Data: 0},
	"stone_shovel":                   {ID: 273, Data: 0},
	"stone_pickaxe":                  {ID: 274, Data: 0},
	"stone_axe":                      {ID: 275, Data: 0},
	"diamond_sword":                  {ID: 276, Data: 0},
	"diamond_shovel":                 {ID: 277, Data: 0},
	"diamond_pickaxe":                {ID: 278, Data: 0},
	"diamond_axe":                    {ID: 279, Data: 0},
	"stick":                          {ID: 280, Data: 0},
	"bowl":                           {ID: 281, Data: 0},
	"mushroom_stew":                  {ID: 282, Data: 0},
	"golden_sword":                   {ID: 283, Data: 0},
	"golden_shovel":                  {ID: 284, Data: 0},
	"golden_pickaxe":                 {ID: 285, Data: 0},
	"golden_axe":                     {ID: 286, Data: 0},
	"string":                         {ID: 287, Data: 0},
	"feather":                        {ID: 288, Data: 0},
	"gunpowder":                      {ID: 289, Data: 0},
	"wooden_hoe":                     {ID: 290, Data: 0},
	"stone_hoe":                      {ID: 291, Data: 0},
	"iron_hoe":                       {ID: 292, Data: 0},
	"diamond_hoe":                    {ID: 293, Data: 0},
	"golden_hoe":                     {ID: 294, Data: 0},
	"wheat_seeds":                    {ID: 295, Data: 0},
	"wheat":                          {ID: 296, Data: 0},
	"bread":                          {ID: 297, Data: 0},
	"leather_helmet":                 {ID: 298, Data: 0},
	"leather_chestplate":             {ID: 299, Data: 0},
	"leather_leggings":               {ID: 300, Data: 0},
	"leather_boots":                  {ID: 301, Data: 0},
	"chainmail_helmet":               {ID: 302, Data: 0},
	"chainmail_chestplate":           {ID: 303, Data: 0},
	"chainmail_leggings":             {ID: 304, Data: 0},
	"chainmail_boots":                {ID: 305, Data: 0},
	"iron_helmet":                    {ID: 306, Data: 0},
	"iron_chestplate":                {ID: 307, Data: 0},
	"iron_leggings":                  {ID: 308, Data: 0},
	"iron_boots":                     {ID: 309, Data: 0},
	"diamond_helmet":                 {ID: 310, Data: 0},
	"diamond_chestplate":             {ID: 311, Data: 0},
	"diamond_leggings":               {ID: 312, Data: 0},
	"diamond_boots":                  {ID: 313, Data: 0},
	"golden_helmet":                  {ID: 314, Data: 0},
	"golden_chestplate":              {ID: 315, Data: 0},
	"golden_leggings":                {ID: 316, Data: 0},
	"golden_boots":                   {ID: 317, Data: 0},
	"flint":                          {ID: 318, Data: 0},
	"porkchop":                       {ID: 319, Data: 0},
	"cooked_porkchop":                {ID: 320, Data: 0},
	"painting":                       {ID: 321, Data: 0},
	"golden_apple":                   {ID: 322, Data: 0},
	"golden_apple:1":                 {ID: 322, Data: 1},
	"sign":                           {ID: 323, Data: 0},
	"wooden_door":                    {ID: 324, Data: 0},
	"bucket":                         {ID: 325, Data: 0},
	"water_bucket":                   {ID: 326, Data: 0},
	"lava_bucket":                    {ID: 327, Data: 0},
	"minecart":                       {ID: 328, Data: 0},
	"saddle":                         {ID: 329, Data: 0},
	"iron_door":                      {ID: 330, Data: 0},
	"redstone":                       {ID: 331, Data: 0},
	"snowball":                       {ID: 332, Data: 0},
	"boat":                           {ID: 333, Data: 0},
	"leather":                        {ID: 334, Data: 0},
	"milk_bucket":                    {ID: 335, Data: 0},
	"brick":                          {ID: 336, Data: 0},
	"clay_ball":                      {ID: 337, Data: 0},
	"reeds":                          {ID: 338, Data: 0},
	"paper":                          {ID: 339, Data: 0},
	"book":                           {ID: 340, Data: 0},
	"slime_ball":                     {ID: 341, Data: 0},
	"chest_minecart":                 {ID: 342, Data: 0},
	"furnace_minecart":               {ID: 343, Data: 0},
	"egg":                            {ID: 344, Data: 0},
	"compass":                        {ID: 345, Data: 0},
	"fishing_rod":                    {ID: 346, Data: 0},
	"clock":                          {ID: 347, Data: 0},
	"glowstone_dust":                 {ID: 348, Data: 0},
	"fish":                           {ID: 349, Data: 0},
	"fish:1":                         {ID: 349, Data: 1},
	"fish:2":                         {ID: 349, Data: 2},
	"fish:3":                         {ID: 349, Data: 3},
	"cooked_fish":                    {ID: 350, Data: 0},
	"dye":                            {ID: 351, Data: 0},
	"dye:1":                          {ID: 351, Data: 1},
	"dye:2":                          {ID: 351, Data: 2},
	"dye:3":                          {ID: 351, Data: 3},
	"dye:4":                          {ID: 351, Data: 4},
	"dye:5":                          {ID: 351, Data: 5},
	"dye:6":                          {ID: 351, Data: 6},
	"dye:7":                          {ID: 351, Data: 7},
	"dye:8":                          {ID: 351, Data: 8},
	"dye:9":                          {ID: 351, Data: 9},
	"dye:10":                         {ID: 351, Data: 10},
	"dye:11":                         {ID: 351, Data: 11},
	"dye:12":                         {ID: 351, Data: 12},
	"dye:13":                         {ID: 351, Data: 13},
	"dye:14":                         {ID: 351, Data: 14},
	"dye:15":                         {ID: 351, Data: 15},
	"bone":                           {ID: 352, Data: 0},
	"sugar":                          {ID: 353, Data: 0},
	"cake":                           {ID: 354, Data: 0},
	"bed":                            {ID: 355, Data: 0},
	"repeater":                       {ID: 356, Data: 0},
	"cookie":                         {ID: 357, Data: 0},
	"filled_map":                     {ID: 358, Data: 0},
	"shears":                         {ID: 359, Data: 0},
	"melon":                          {ID: 360, Data: 0},
	"pumpkin_seeds":                  {ID: 361, Data: 0},
	"melon_seeds":                    {ID: 362, Data: 0},
	"beef":                           {ID: 363, Data: 0},
	"cooked_beef":                    {ID: 364, Data: 0},
	"chicken":                        {ID: 365, Data: 0},
	"cooked_chicken":                 {ID: 366, Data: 0},
	"rotten_flesh":                   {ID: 367, Data: 0},
	"ender_pearl":                    {ID: 368, Data: 0},
	"blaze_rod":                      {ID: 369, Data: 0},
	"ghast_tear":                     {ID: 370, Data: 0},
	"gold_nugget":                    {ID: 371, Data: 0},
	"nether_wart":                    {ID: 372, Data: 0},
	"potion":                         {ID: 373, Data: 0},
	"glass_bottle":                   {ID: 374, Data: 0},
	"spider_eye":                     {ID: 375, Data: 0},
	"fermented_spider_eye":           {ID: 376, Data: 0},
	"blaze_powder":                   {ID: 377, Data: 0},
	"magma_cream":                    {ID: 378, Data: 0},
	"brewing_stand":                  {ID: 379, Data: 0},
	"cauldron":                       {ID: 380, Data: 0},
	"ender_eye":                      {ID: 381, Data: 0},
	"speckled_melon":                 {ID: 382, Data: 0},
	"spawn_egg":                      {ID: 383, Data: 0},
	"experience_bottle":              {ID: 384, Data: 0},
	"fire_charge":                    {ID: 385, Data: 0},
	"writable_book":                  {ID: 386, Data: 0},
	"written_book":                   {ID: 387, Data: 0},
	"emerald":                        {ID: 388, Data: 0},
	"item_frame":                     {ID: 389, Data: 0},
	"flower_pot":                     {ID: 390, Data: 0},
	"flower_pot:1":                   {ID: 390, Data: 1},
	"flower_pot:2":                   {ID: 390, Data: 2},
	"flower_pot:3":                   {ID: 390, Data: 3},
	"flower_pot:4":                   {ID: 390, Data: 4},
	"flower_pot:5":                   {ID: 390, Data: 5},
	"flower_pot:6":                   {ID: 390, Data: 6},
	"flower_pot:7":                   {ID: 390, Data: 7},
	"flower_pot:8":                   {ID: 390, Data: 8},
	"flower_pot:9":                   {ID: 390, Data: 9},
	"flower_pot:10":                  {ID: 390, Data: 10},
	"flower_pot:11":                  {ID: 390, Data: 11},
	"flower_pot:12":                  {ID: 390, Data: 12},
	"flower_pot:13":                  {ID: 390, Data: 13},
	"carrot":                         {ID: 391, Data: 0},
	"potato":                         {ID: 392, Data: 0},
	"baked_potato":                   {ID: 393, Data: 0},
	"poisonous_potato":               {ID: 394, Data: 0},
	"map":                            {ID: 395, Data: 0},
	"golden_carrot":                  {ID: 396, Data: 0},
	"skull":                          {ID: 397, Data: 0},
	"skull:1":                        {ID: 397, Data: 1},
	"skull:2":                        {ID: 397, Data: 2},
	"skull:3":                        {ID: 397, Data: 3},
	//"skull:4":                          {ID: 397, Data: 4},
	"carrot_on_a_stick":      {ID: 398, Data: 0},
	"nether_star":            {ID: 399, Data: 0},
	"pumpkin_pie":            {ID: 400, Data: 0},
	"fireworks":              {ID: 401, Data: 0},
	"firework_charge":        {ID: 402, Data: 0},
	"enchanted_book":         {ID: 403, Data: 0},
	"comparator":             {ID: 404, Data: 0},
	"netherbrick":            {ID: 405, Data: 0},
	"quartz":                 {ID: 406, Data: 0},
	"tnt_minecart":           {ID: 407, Data: 0},
	"hopper_minecart":        {ID: 408, Data: 0},
	"prismarine_shard":       {ID: 409, Data: 0},
	"prismarine_crystals":    {ID: 410, Data: 0},
	"rabbit":                 {ID: 411, Data: 0},
	"cooked_rabbit":          {ID: 412, Data: 0},
	"rabbit_stew":            {ID: 413, Data: 0},
	"rabbit_foot":            {ID: 414, Data: 0},
	"rabbit_hide":            {ID: 415, Data: 0},
	"armor_stand":            {ID: 416, Data: 0},
	"iron_horse_armor":       {ID: 417, Data: 0},
	"golden_horse_armor":     {ID: 418, Data: 0},
	"diamond_horse_armor":    {ID: 419, Data: 0},
	"lead":                   {ID: 420, Data: 0},
	"name_tag":               {ID: 421, Data: 0},
	"command_block_minecart": {ID: 422, Data: 0},
	"mutton":                 {ID: 423, Data: 0},
	"cooked_mutton":          {ID: 424, Data: 0},
	"banner":                 {ID: 425, Data: 0},
	"end_crystal":            {ID: 426, Data: 0},
	"chorus_fruit":           {ID: 432, Data: 0},
	"chorus_fruit_popped":    {ID: 433, Data: 0},
	"beetroot":               {ID: 434, Data: 0},
	"beetroot_seeds":         {ID: 435, Data: 0},
	"beetroot_soup":          {ID: 436, Data: 0},
	"dragon_breath":          {ID: 437, Data: 0},
	"splash_potion":          {ID: 438, Data: 0},
	"spectral_arrow":         {ID: 439, Data: 0},
	"tipped_arrow":           {ID: 440, Data: 0},
	"lingering_potion":       {ID: 441, Data: 0},
	"shield":                 {ID: 442, Data: 0},
	"elytra":                 {ID: 443, Data: 0},
	"spruce_boat":            {ID: 444, Data: 0},
	"birch_boat":             {ID: 445, Data: 0},
	"jungle_boat":            {ID: 446, Data: 0},
	"acacia_boat":            {ID: 447, Data: 0},
	"dark_oak_boat":          {ID: 448, Data: 0},
	"totem_of_undying":       {ID: 449, Data: 0},
	"shulker_shell":          {ID: 450, Data: 0},
	"iron_nugget":            {ID: 452, Data: 0},
	"knowledge_book":         {ID: 453, Data: 0},
	"record_13":              {ID: 2256, Data: 0},
	"record_cat":             {ID: 2257, Data: 0},
	"record_blocks":          {ID: 2258, Data: 0},
	"record_chirp":           {ID: 2259, Data: 0},
	"record_far":             {ID: 2260, Data: 0},
	"record_mall":            {ID: 2261, Data: 0},
	"record_mellohi":         {ID: 2262, Data: 0},
	"record_stal":            {ID: 2263, Data: 0},
	"record_strad":           {ID: 2264, Data: 0},
	"record_ward":            {ID: 2265, Data: 0},
	"record_11":              {ID: 2266, Data: 0},
	"record_wait":            {ID: 2267, Data: 0},
}

var ItemIDToName = map[int]string{
	0:    "air",
	1:    "stone",
	2:    "grass",
	3:    "dirt",
	4:    "cobblestone",
	5:    "planks",
	6:    "sapling",
	7:    "bedrock",
	8:    "flowing_water",
	9:    "water",
	10:   "flowing_lava",
	11:   "lava",
	12:   "sand",
	13:   "gravel",
	14:   "gold_ore",
	15:   "iron_ore",
	16:   "coal_ore",
	17:   "log",
	18:   "leaves",
	19:   "sponge",
	20:   "glass",
	21:   "lapis_ore",
	22:   "lapis_block",
	23:   "dispenser",
	24:   "sandstone",
	25:   "noteblock",
	26:   "bed",
	27:   "golden_rail",
	28:   "detector_rail",
	29:   "sticky_piston",
	30:   "web",
	31:   "tallgrass",
	32:   "deadbush",
	33:   "piston",
	34:   "piston_head",
	35:   "wool",
	36:   "piston_extension",
	37:   "yellow_flower",
	38:   "red_flower",
	39:   "brown_mushroom",
	40:   "red_mushroom",
	41:   "gold_block",
	42:   "iron_block",
	43:   "double_stone_slab",
	44:   "stone_slab",
	45:   "brick_block",
	46:   "tnt",
	47:   "bookshelf",
	48:   "mossy_cobblestone",
	49:   "obsidian",
	50:   "torch",
	51:   "fire",
	52:   "mob_spawner",
	53:   "oak_stairs",
	54:   "chest",
	55:   "redstone_wire",
	56:   "diamond_ore",
	57:   "diamond_block",
	58:   "crafting_table",
	59:   "wheat",
	60:   "farmland",
	61:   "furnace",
	62:   "lit_furnace",
	63:   "standing_sign",
	64:   "wooden_door",
	65:   "ladder",
	66:   "rail",
	67:   "stone_stairs",
	68:   "wall_sign",
	69:   "lever",
	70:   "stone_pressure_plate",
	71:   "iron_door",
	72:   "wooden_pressure_plate",
	73:   "redstone_ore",
	74:   "lit_redstone_ore",
	75:   "unlit_redstone_torch",
	76:   "redstone_torch",
	77:   "stone_button",
	78:   "snow_layer",
	79:   "ice",
	80:   "snow",
	81:   "cactus",
	82:   "clay",
	83:   "reeds",
	84:   "jukebox",
	85:   "fence",
	86:   "pumpkin",
	87:   "netherrack",
	88:   "soul_sand",
	89:   "glowstone",
	90:   "portal",
	91:   "lit_pumpkin",
	92:   "cake",
	93:   "unpowered_repeater",
	94:   "powered_repeater",
	95:   "stained_glass",
	96:   "trapdoor",
	97:   "monster_egg",
	98:   "stonebrick",
	99:   "brown_mushroom_block",
	100:  "red_mushroom_block",
	101:  "iron_bars",
	102:  "glass_pane",
	103:  "melon_block",
	104:  "pumpkin_stem",
	105:  "melon_stem",
	106:  "vine",
	107:  "fence_gate",
	108:  "brick_stairs",
	109:  "stone_brick_stairs",
	110:  "mycelium",
	111:  "waterlily",
	112:  "nether_brick",
	113:  "nether_brick_fence",
	114:  "nether_brick_stairs",
	115:  "nether_wart",
	116:  "enchanting_table",
	117:  "brewing_stand",
	118:  "cauldron",
	119:  "end_portal",
	120:  "end_portal_frame",
	121:  "end_stone",
	122:  "dragon_egg",
	123:  "redstone_lamp",
	124:  "lit_redstone_lamp",
	125:  "double_wooden_slab",
	126:  "wooden_slab",
	127:  "cocoa",
	128:  "sandstone_stairs",
	129:  "emerald_ore",
	130:  "ender_chest",
	131:  "tripwire_hook",
	132:  "tripwire",
	133:  "emerald_block",
	134:  "spruce_stairs",
	135:  "birch_stairs",
	136:  "jungle_stairs",
	137:  "command_block",
	138:  "beacon",
	139:  "cobblestone_wall",
	140:  "flower_pot",
	141:  "carrots",
	142:  "potatoes",
	143:  "wooden_button",
	144:  "skull",
	145:  "anvil",
	146:  "trapped_chest",
	147:  "light_weighted_pressure_plate",
	148:  "heavy_weighted_pressure_plate",
	149:  "unpowered_comparator",
	150:  "powered_comparator",
	151:  "daylight_detector",
	152:  "redstone_block",
	153:  "quartz_ore",
	154:  "hopper",
	155:  "quartz_block",
	156:  "quartz_stairs",
	157:  "activator_rail",
	158:  "dropper",
	159:  "stained_hardened_clay",
	160:  "stained_glass_pane",
	161:  "leaves2",
	162:  "log2",
	163:  "acacia_stairs",
	164:  "dark_oak_stairs",
	165:  "slime",
	166:  "barrier",
	167:  "iron_trapdoor",
	168:  "prismarine",
	169:  "sea_lantern",
	170:  "hay_block",
	171:  "carpet",
	172:  "hardened_clay",
	173:  "coal_block",
	174:  "packed_ice",
	175:  "double_plant",
	176:  "standing_banner",
	177:  "wall_banner",
	178:  "daylight_detector_inverted",
	179:  "red_sandstone",
	180:  "red_sandstone_stairs",
	181:  "double_stone_slab2",
	182:  "stone_slab2",
	183:  "spruce_fence_gate",
	184:  "birch_fence_gate",
	185:  "jungle_fence_gate",
	186:  "dark_oak_fence_gate",
	187:  "acacia_fence_gate",
	188:  "spruce_fence",
	189:  "birch_fence",
	190:  "jungle_fence",
	191:  "dark_oak_fence",
	192:  "acacia_fence",
	193:  "spruce_door",
	194:  "birch_door",
	195:  "jungle_door",
	196:  "acacia_door",
	197:  "dark_oak_door",
	198:  "end_rod",
	199:  "chorus_plant",
	200:  "chorus_flower",
	201:  "purpur_block",
	202:  "purpur_pillar",
	203:  "purpur_stairs",
	204:  "purpur_double_slab",
	205:  "purpur_slab",
	206:  "end_bricks",
	207:  "beetroots",
	208:  "grass_path",
	209:  "end_gateway",
	210:  "repeating_command_block",
	211:  "chain_command_block",
	212:  "frosted_ice",
	213:  "magma",
	214:  "nether_wart_block",
	215:  "red_nether_brick",
	216:  "bone_block",
	217:  "structure_void",
	218:  "observer",
	219:  "white_shulker_box",
	220:  "orange_shulker_box",
	221:  "magenta_shulker_box",
	222:  "light_blue_shulker_box",
	223:  "yellow_shulker_box",
	224:  "lime_shulker_box",
	225:  "pink_shulker_box",
	226:  "gray_shulker_box",
	227:  "light_gray_shulker_box",
	228:  "cyan_shulker_box",
	229:  "purple_shulker_box",
	230:  "blue_shulker_box",
	231:  "brown_shulker_box",
	232:  "green_shulker_box",
	233:  "red_shulker_box",
	234:  "black_shulker_box",
	235:  "white_glazed_terracotta",
	236:  "orange_glazed_terracotta",
	237:  "magenta_glazed_terracotta",
	238:  "light_blue_glazed_terracotta",
	239:  "yellow_glazed_terracotta",
	240:  "lime_glazed_terracotta",
	241:  "pink_glazed_terracotta",
	242:  "gray_glazed_terracotta",
	243:  "light_gray_glazed_terracotta",
	244:  "cyan_glazed_terracotta",
	245:  "purple_glazed_terracotta",
	246:  "blue_glazed_terracotta",
	247:  "brown_glazed_terracotta",
	248:  "green_glazed_terracotta",
	249:  "red_glazed_terracotta",
	250:  "black_glazed_terracotta",
	251:  "concrete",
	252:  "concrete_powder",
	255:  "structure_block",
	256:  "iron_shovel",
	257:  "iron_pickaxe",
	258:  "iron_axe",
	259:  "flint_and_steel",
	260:  "apple",
	261:  "bow",
	262:  "arrow",
	263:  "coal",
	264:  "diamond",
	265:  "iron_ingot",
	266:  "gold_ingot",
	267:  "iron_sword",
	268:  "wooden_sword",
	269:  "wooden_shovel",
	270:  "wooden_pickaxe",
	271:  "wooden_axe",
	272:  "stone_sword",
	273:  "stone_shovel",
	274:  "stone_pickaxe",
	275:  "stone_axe",
	276:  "diamond_sword",
	277:  "diamond_shovel",
	278:  "diamond_pickaxe",
	279:  "diamond_axe",
	280:  "stick",
	281:  "bowl",
	282:  "mushroom_stew",
	283:  "golden_sword",
	284:  "golden_shovel",
	285:  "golden_pickaxe",
	286:  "golden_axe",
	287:  "string",
	288:  "feather",
	289:  "gunpowder",
	290:  "wooden_hoe",
	291:  "stone_hoe",
	292:  "iron_hoe",
	293:  "diamond_hoe",
	294:  "golden_hoe",
	295:  "wheat_seeds",
	296:  "wheat",
	297:  "bread",
	298:  "leather_helmet",
	299:  "leather_chestplate",
	300:  "leather_leggings",
	301:  "leather_boots",
	302:  "chainmail_helmet",
	303:  "chainmail_chestplate",
	304:  "chainmail_leggings",
	305:  "chainmail_boots",
	306:  "iron_helmet",
	307:  "iron_chestplate",
	308:  "iron_leggings",
	309:  "iron_boots",
	310:  "diamond_helmet",
	311:  "diamond_chestplate",
	312:  "diamond_leggings",
	313:  "diamond_boots",
	314:  "golden_helmet",
	315:  "golden_chestplate",
	316:  "golden_leggings",
	317:  "golden_boots",
	318:  "flint",
	319:  "porkchop",
	320:  "cooked_porkchop",
	321:  "painting",
	322:  "golden_apple",
	323:  "sign",
	324:  "wooden_door",
	325:  "bucket",
	326:  "water_bucket",
	327:  "lava_bucket",
	328:  "minecart",
	329:  "saddle",
	330:  "iron_door",
	331:  "redstone",
	332:  "snowball",
	333:  "boat",
	334:  "leather",
	335:  "milk_bucket",
	336:  "brick",
	337:  "clay_ball",
	338:  "reeds",
	339:  "paper",
	340:  "book",
	341:  "slime_ball",
	342:  "chest_minecart",
	343:  "furnace_minecart",
	344:  "egg",
	345:  "compass",
	346:  "fishing_rod",
	347:  "clock",
	348:  "glowstone_dust",
	349:  "fish",
	350:  "cooked_fish",
	351:  "dye",
	352:  "bone",
	353:  "sugar",
	354:  "cake",
	355:  "bed",
	356:  "repeater",
	357:  "cookie",
	358:  "filled_map",
	359:  "shears",
	360:  "melon",
	361:  "pumpkin_seeds",
	362:  "melon_seeds",
	363:  "beef",
	364:  "cooked_beef",
	365:  "chicken",
	366:  "cooked_chicken",
	367:  "rotten_flesh",
	368:  "ender_pearl",
	369:  "blaze_rod",
	370:  "ghast_tear",
	371:  "gold_nugget",
	372:  "nether_wart",
	373:  "potion",
	374:  "glass_bottle",
	375:  "spider_eye",
	376:  "fermented_spider_eye",
	377:  "blaze_powder",
	378:  "magma_cream",
	379:  "brewing_stand",
	380:  "cauldron",
	381:  "ender_eye",
	382:  "speckled_melon",
	383:  "spawn_egg",
	384:  "experience_bottle",
	385:  "fire_charge",
	386:  "writable_book",
	387:  "written_book",
	388:  "emerald",
	389:  "item_frame",
	390:  "flower_pot",
	391:  "carrot",
	392:  "potato",
	393:  "baked_potato",
	394:  "poisonous_potato",
	395:  "map",
	396:  "golden_carrot",
	397:  "skull",
	398:  "carrot_on_a_stick",
	399:  "nether_star",
	400:  "pumpkin_pie",
	401:  "fireworks",
	402:  "firework_charge",
	403:  "enchanted_book",
	404:  "comparator",
	405:  "netherbrick",
	406:  "quartz",
	407:  "tnt_minecart",
	408:  "hopper_minecart",
	409:  "prismarine_shard",
	410:  "prismarine_crystals",
	411:  "rabbit",
	412:  "cooked_rabbit",
	413:  "rabbit_stew",
	414:  "rabbit_foot",
	415:  "rabbit_hide",
	416:  "armor_stand",
	417:  "iron_horse_armor",
	418:  "golden_horse_armor",
	419:  "diamond_horse_armor",
	420:  "lead",
	421:  "name_tag",
	422:  "command_block_minecart",
	423:  "mutton",
	424:  "cooked_mutton",
	425:  "banner",
	426:  "end_crystal",
	427:  "spruce_door",
	428:  "birch_door",
	429:  "jungle_door",
	430:  "acacia_door",
	431:  "dark_oak_door",
	432:  "chorus_fruit",
	433:  "chorus_fruit_popped",
	434:  "beetroot",
	435:  "beetroot_seeds",
	436:  "beetroot_soup",
	437:  "dragon_breath",
	438:  "splash_potion",
	439:  "spectral_arrow",
	440:  "tipped_arrow",
	441:  "lingering_potion",
	442:  "shield",
	443:  "elytra",
	444:  "spruce_boat",
	445:  "birch_boat",
	446:  "jungle_boat",
	447:  "acacia_boat",
	448:  "dark_oak_boat",
	449:  "totem_of_undying",
	450:  "shulker_shell",
	452:  "iron_nugget",
	453:  "knowledge_book",
	2256: "record_13",
	2257: "record_cat",
	2258: "record_blocks",
	2259: "record_chirp",
	2260: "record_far",
	2261: "record_mall",
	2262: "record_mellohi",
	2263: "record_stal",
	2264: "record_strad",
	2265: "record_ward",
	2266: "record_11",
	2267: "record_wait",
}
